#include <map>
#include "layers.h"
namespace backend {

    template<typename T> Layer* createInstance(std::string n) { return new T(n); }

std::map<std::string, Layer*(*)(std::string n)> layer_map = {
/*
	{ "LSTM", &createInstance<LSTM>}, 
	{ "Identity", &createInstance<Identity>}, 
	{ "Abs", &createInstance<Abs>}, 
	{ "BatchNormalization", &createInstance<BatchNormalization>}, 
	{ "Mean", &createInstance<Mean>}, 
	{ "Add", &createInstance<Add>}, 
	{ "GlobalMaxPool", &createInstance<GlobalMaxPool>}, 
	{ "Cast", &createInstance<Cast>}, 
	{ "AveragePool", &createInstance<AveragePool>}, 
	{ "And", &createInstance<And>}, 
	{ "LRN", &createInstance<LRN>}, 
	{ "ArgMax", &createInstance<ArgMax>}, 
	{ "Resize", &createInstance<Resize>}, 
	{ "Expand", &createInstance<Expand>}, 
	{ "Neg", &createInstance<Neg>}, 
	{ "Mul", &createInstance<Mul>}, 
	{ "ArgMin", &createInstance<ArgMin>}, 
	{ "CastMap", &createInstance<CastMap>}, 
	{ "Exp", &createInstance<Exp>}, 
	{ "Div", &createInstance<Div>}, 
	{ "ReverseSequence", &createInstance<ReverseSequence>}, 
	{ "Ceil", &createInstance<Ceil>}, 
	{ "DepthToSpace", &createInstance<DepthToSpace>}, 
	{ "Clip", &createInstance<Clip>}, 
	{ "RNN", &createInstance<RNN>}, 
	{ "Concat", &createInstance<Concat>}, 
	{ "Constant", &createInstance<Constant>}, 
	{ "LpPool", &createInstance<LpPool>}, 
	{ "Conv", &createInstance<Conv>}, 
	{ "Not", &createInstance<Not>}, 
	{ "Gather", &createInstance<Gather>}, 
	{ "ConvTranspose", &createInstance<ConvTranspose>}, 
	{ "Dropout", &createInstance<Dropout>}, 
	{ "LeakyRelu", &createInstance<LeakyRelu>}, 
	{ "Elu", &createInstance<Elu>}, 
	{ "GlobalAveragePool", &createInstance<GlobalAveragePool>}, 
	{ "Gemm", &createInstance<Gemm>}, 
	{ "MaxPool", &createInstance<MaxPool>}, 
	{ "Equal", &createInstance<Equal>}, 
	{ "Tile", &createInstance<Tile>}, 
	{ "Flatten", &createInstance<Flatten>}, 
	{ "Floor", &createInstance<Floor>}, 
	{ "GRU", &createInstance<GRU>}, 
	{ "GlobalLpPool", &createInstance<GlobalLpPool>}, 
	{ "Greater", &createInstance<Greater>}, 
	{ "HardSigmoid", &createInstance<HardSigmoid>}, 
	{ "Selu", &createInstance<Selu>}, 
	{ "Hardmax", &createInstance<Hardmax>}, 
	{ "If", &createInstance<If>}, 
	{ "Min", &createInstance<Min>}, 
	{ "InstanceNormalization", &createInstance<InstanceNormalization>}, 
	{ "Less", &createInstance<Less>}, 
	{ "EyeLike", &createInstance<EyeLike>}, 
	{ "RandomNormal", &createInstance<RandomNormal>}, 
	{ "Slice", &createInstance<Slice>}, 
	{ "PRelu", &createInstance<PRelu>}, 
	{ "Log", &createInstance<Log>}, 
	{ "LogSoftmax", &createInstance<LogSoftmax>}, 
	{ "Loop", &createInstance<Loop>}, 
	{ "LpNormalization", &createInstance<LpNormalization>}, 
	{ "MatMul", &createInstance<MatMul>}, 
	{ "ReduceL2", &createInstance<ReduceL2>}, 
	{ "Max", &createInstance<Max>}, 
	{ "MaxRoiPool", &createInstance<MaxRoiPool>}, 
	{ "Or", &createInstance<Or>}, 
	{ "Pad", &createInstance<Pad>}, 
	{ "RandomUniformLike", &createInstance<RandomUniformLike>}, 
	{ "Reciprocal", &createInstance<Reciprocal>}, 
	{ "Pow", &createInstance<Pow>}, 
	{ "RandomNormalLike", &createInstance<RandomNormalLike>}, 
	{ "OneHot", &createInstance<OneHot>}, 
	{ "RandomUniform", &createInstance<RandomUniform>}, 
	{ "ReduceL1", &createInstance<ReduceL1>}, 
	{ "ReduceLogSum", &createInstance<ReduceLogSum>}, 
	{ "ReduceLogSumExp", &createInstance<ReduceLogSumExp>}, 
	{ "ReduceMax", &createInstance<ReduceMax>}, 
	{ "OneHotEncoder", &createInstance<OneHotEncoder>}, 
	{ "IsNaN", &createInstance<IsNaN>}, 
	{ "ReduceMean", &createInstance<ReduceMean>}, 
	{ "ReduceMin", &createInstance<ReduceMin>}, 
	{ "TreeEnsembleRegressor", &createInstance<TreeEnsembleRegressor>}, 
	{ "ReduceProd", &createInstance<ReduceProd>}, 
	{ "ReduceSum", &createInstance<ReduceSum>}, 
	{ "ReduceSumSquare", &createInstance<ReduceSumSquare>}, 
	{ "Relu", &createInstance<Relu>}, 
	{ "Reshape", &createInstance<Reshape>}, 
	{ "Shape", &createInstance<Shape>}, 
	{ "Sigmoid", &createInstance<Sigmoid>}, 
	{ "Size", &createInstance<Size>}, 
	{ "Softmax", &createInstance<Softmax>}, 
	{ "Softplus", &createInstance<Softplus>}, 
	{ "Softsign", &createInstance<Softsign>}, 
	{ "SpaceToDepth", &createInstance<SpaceToDepth>}, 
	{ "TfIdfVectorizer", &createInstance<TfIdfVectorizer>}, 
	{ "Split", &createInstance<Split>}, 
	{ "Imputer", &createInstance<Imputer>}, 
	{ "Sqrt", &createInstance<Sqrt>}, 
	{ "Squeeze", &createInstance<Squeeze>}, 
	{ "TopK", &createInstance<TopK>}, 
	{ "Sub", &createInstance<Sub>}, 
	{ "Sum", &createInstance<Sum>}, 
	{ "Shrink", &createInstance<Shrink>}, 
	{ "Tanh", &createInstance<Tanh>}, 
	{ "Transpose", &createInstance<Transpose>}, 
	{ "Unsqueeze", &createInstance<Unsqueeze>}, 
	{ "SVMClassifier", &createInstance<SVMClassifier>}, 
	{ "Xor", &createInstance<Xor>}, 
	{ "Acos", &createInstance<Acos>}, 
	{ "Asin", &createInstance<Asin>}, 
	{ "Atan", &createInstance<Atan>}, 
	{ "Cos", &createInstance<Cos>}, 
	{ "Sin", &createInstance<Sin>}, 
	{ "Tan", &createInstance<Tan>}, 
	{ "Multinomial", &createInstance<Multinomial>}, 
	{ "Scan", &createInstance<Scan>}, 
	{ "Compress", &createInstance<Compress>}, 
	{ "ConstantOfShape", &createInstance<ConstantOfShape>}, 
	{ "MaxUnpool", &createInstance<MaxUnpool>}, 
	{ "Scatter", &createInstance<Scatter>}, 
	{ "Sinh", &createInstance<Sinh>}, 
	{ "Cosh", &createInstance<Cosh>}, 
	{ "Asinh", &createInstance<Asinh>}, 
	{ "Acosh", &createInstance<Acosh>}, 
	{ "NonMaxSuppression", &createInstance<NonMaxSuppression>}, 
	{ "Atanh", &createInstance<Atanh>}, 
	{ "Sign", &createInstance<Sign>}, 
	{ "Erf", &createInstance<Erf>}, 
	{ "Where", &createInstance<Where>}, 
	{ "NonZero", &createInstance<NonZero>}, 
	{ "MeanVarianceNormalization", &createInstance<MeanVarianceNormalization>}, 
	{ "StringNormalizer", &createInstance<StringNormalizer>}, 
	{ "Mod", &createInstance<Mod>}, 
	{ "ThresholdedRelu", &createInstance<ThresholdedRelu>}, 
	{ "MatMulInteger", &createInstance<MatMulInteger>}, 
	{ "QLinearMatMul", &createInstance<QLinearMatMul>}, 
	{ "ConvInteger", &createInstance<ConvInteger>}, 
	{ "QLinearConv", &createInstance<QLinearConv>}, 
	{ "QuantizeLinear", &createInstance<QuantizeLinear>}, 
	{ "DequantizeLinear", &createInstance<DequantizeLinear>}, 
	{ "IsInf", &createInstance<IsInf>}, 
	{ "RoiAlign", &createInstance<RoiAlign>}, 
	{ "ArrayFeatureExtractor", &createInstance<ArrayFeatureExtractor>}, 
	{ "Binarizer", &createInstance<Binarizer>}, 
	{ "CategoryMapper", &createInstance<CategoryMapper>}, 
	{ "DictVectorizer", &createInstance<DictVectorizer>}, 
	{ "FeatureVectorizer", &createInstance<FeatureVectorizer>}, 
	{ "LabelEncoder", &createInstance<LabelEncoder>}, 
	{ "LinearClassifier", &createInstance<LinearClassifier>}, 
	{ "LinearRegressor", &createInstance<LinearRegressor>}, 
	{ "Normalizer", &createInstance<Normalizer>}, 
	{ "SVMRegressor", &createInstance<SVMRegressor>}, 
	{ "Scaler", &createInstance<Scaler>}, 
	{ "TreeEnsembleClassifier", &createInstance<TreeEnsembleClassifier>}, 
	{ "ZipMap", &createInstance<ZipMap>}
*/
};


std::map<std::string, std::map<std::string, std::string> > parameter_map = {
/*
{ "LSTM", {{"X_input", {"inputs", "Tensor*"} }, {"W_input", {"inputs", "Tensor*"} }, {"R_input", {"inputs", "Tensor*"} }, {"B_input_opt", {"optional_input", "Tensor*"} }, {"sequence_lens_input_opt", {"optional_input", "Tensor*"} }, {"initial_h_input_opt", {"optional_input", "Tensor*"} }, {"initial_c_input_opt", {"optional_input", "Tensor*"} }, {"P_input_opt", {"optional_input", "Tensor*"} }, {"Y_output_opt", {"optional_output", "Tensor*"} }, {"Y_h_output_opt", {"optional_output", "Tensor*"} }, {"Y_c_output_opt", {"optional_output", "Tensor*"} }, {"activation_alpha", {"optional_parameters", "Tensor*"} }, {"activation_beta", {"optional_parameters", "Tensor*"} }, {"activations", {"optional_parameters", "Tensor*"} }, {"clip", {"optional_parameters", "float"} }, {"direction", {"optional_parameters", "int"} }, {"hidden_size", {"optional_parameters", "int"} }, {"input_forget", {"optional_parameters", "int"} }} }, 
{ "Identity", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Abs", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "BatchNormalization", {{"X_input", {"inputs", "Tensor*"} }, {"scale_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"mean_input", {"inputs", "Tensor*"} }, {"var_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"mean_output_opt", {"optional_output", "Tensor*"} }, {"var_output_opt", {"optional_output", "Tensor*"} }, {"saved_mean_output_opt", {"optional_output", "Tensor*"} }, {"saved_var_output_opt", {"optional_output", "Tensor*"} }, {"epsilon", {"optional_parameters", "float"} }, {"momentum", {"optional_parameters", "float"} }} }, 
{ "Mean", {{"mean_output", {"outputs", "Tensor*"} }} }, 
{ "Add", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "GlobalMaxPool", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Cast", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"to", {"parameters", "int"} }} }, 
{ "AveragePool", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"kernel_shape", {"parameters", "Shape_t"} }, {"auto_pad", {"optional_parameters", "int"} }, {"ceil_mode", {"optional_parameters", "int"} }, {"count_include_pad", {"optional_parameters", "int"} }, {"pads", {"optional_parameters", "Shape_t"} }, {"strides", {"optional_parameters", "Shape_t"} }} }, 
{ "And", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "LRN", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"size", {"parameters", "int"} }, {"alpha", {"optional_parameters", "float"} }, {"beta", {"optional_parameters", "float"} }, {"bias", {"optional_parameters", "float"} }} }, 
{ "ArgMax", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "Resize", {{"X_input", {"inputs", "Tensor*"} }, {"scales_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"mode", {"optional_parameters", "int"} }} }, 
{ "Expand", {{"input_input", {"inputs", "Tensor*"} }, {"shape_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Neg", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Mul", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "ArgMin", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "CastMap", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"cast_to", {"optional_parameters", "int"} }, {"map_form", {"optional_parameters", "int"} }, {"max_map", {"optional_parameters", "int"} }} }, 
{ "Exp", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Div", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "ReverseSequence", {{"input_input", {"inputs", "Tensor*"} }, {"sequence_lens_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"batch_axis", {"optional_parameters", "int"} }, {"time_axis", {"optional_parameters", "int"} }} }, 
{ "Ceil", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "DepthToSpace", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"blocksize", {"parameters", "int"} }} }, 
{ "Clip", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"max", {"optional_parameters", "float"} }, {"min", {"optional_parameters", "float"} }} }, 
{ "RNN", {{"X_input", {"inputs", "Tensor*"} }, {"W_input", {"inputs", "Tensor*"} }, {"R_input", {"inputs", "Tensor*"} }, {"B_input_opt", {"optional_input", "Tensor*"} }, {"sequence_lens_input_opt", {"optional_input", "Tensor*"} }, {"initial_h_input_opt", {"optional_input", "Tensor*"} }, {"Y_output_opt", {"optional_output", "Tensor*"} }, {"Y_h_output_opt", {"optional_output", "Tensor*"} }, {"activation_alpha", {"optional_parameters", "Tensor*"} }, {"activation_beta", {"optional_parameters", "Tensor*"} }, {"activations", {"optional_parameters", "Tensor*"} }, {"clip", {"optional_parameters", "float"} }, {"direction", {"optional_parameters", "int"} }, {"hidden_size", {"optional_parameters", "int"} }} }, 
{ "Concat", {{"concat_result_output", {"outputs", "Tensor*"} }, {"axis", {"parameters", "int"} }} }, 
{ "Constant", {{"output_output", {"outputs", "Tensor*"} }, {"value", {"parameters", "Tensor*"} }} }, 
{ "LpPool", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"kernel_shape", {"parameters", "Shape_t"} }, {"auto_pad", {"optional_parameters", "int"} }, {"p", {"optional_parameters", "int"} }, {"pads", {"optional_parameters", "Shape_t"} }, {"strides", {"optional_parameters", "Shape_t"} }} }, 
{ "Conv", {{"X_input", {"inputs", "Tensor*"} }, {"W_input", {"inputs", "Tensor*"} }, {"B_input_opt", {"optional_input", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"auto_pad", {"optional_parameters", "int"} }, {"dilations", {"optional_parameters", "Shape_t"} }, {"group", {"optional_parameters", "int"} }, {"kernel_shape", {"optional_parameters", "Shape_t"} }, {"pads", {"optional_parameters", "Shape_t"} }, {"strides", {"optional_parameters", "Shape_t"} }} }, 
{ "Not", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Gather", {{"data_input", {"inputs", "Tensor*"} }, {"indices_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }} }, 
{ "ConvTranspose", {{"X_input", {"inputs", "Tensor*"} }, {"W_input", {"inputs", "Tensor*"} }, {"B_input_opt", {"optional_input", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"auto_pad", {"optional_parameters", "int"} }, {"dilations", {"optional_parameters", "Shape_t"} }, {"group", {"optional_parameters", "int"} }, {"kernel_shape", {"optional_parameters", "Shape_t"} }, {"output_padding", {"optional_parameters", "Shape_t"} }, {"output_shape", {"optional_parameters", "Shape_t"} }, {"pads", {"optional_parameters", "Shape_t"} }, {"strides", {"optional_parameters", "Shape_t"} }} }, 
{ "Dropout", {{"data_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"mask_output_opt", {"optional_output", "Tensor*"} }, {"ratio", {"optional_parameters", "float"} }} }, 
{ "LeakyRelu", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"alpha", {"optional_parameters", "float"} }} }, 
{ "Elu", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"alpha", {"optional_parameters", "float"} }} }, 
{ "GlobalAveragePool", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Gemm", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"alpha", {"optional_parameters", "float"} }, {"beta", {"optional_parameters", "float"} }, {"transA", {"optional_parameters", "int"} }, {"transB", {"optional_parameters", "int"} }} }, 
{ "MaxPool", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"Indices_output_opt", {"optional_output", "Tensor*"} }, {"kernel_shape", {"parameters", "Shape_t"} }, {"auto_pad", {"optional_parameters", "int"} }, {"ceil_mode", {"optional_parameters", "int"} }, {"dilations", {"optional_parameters", "Shape_t"} }, {"pads", {"optional_parameters", "Shape_t"} }, {"storage_order", {"optional_parameters", "int"} }, {"strides", {"optional_parameters", "Shape_t"} }} }, 
{ "Equal", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "Tile", {{"input_input", {"inputs", "Tensor*"} }, {"repeats_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Flatten", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }} }, 
{ "Floor", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "GRU", {{"X_input", {"inputs", "Tensor*"} }, {"W_input", {"inputs", "Tensor*"} }, {"R_input", {"inputs", "Tensor*"} }, {"B_input_opt", {"optional_input", "Tensor*"} }, {"sequence_lens_input_opt", {"optional_input", "Tensor*"} }, {"initial_h_input_opt", {"optional_input", "Tensor*"} }, {"Y_output_opt", {"optional_output", "Tensor*"} }, {"Y_h_output_opt", {"optional_output", "Tensor*"} }, {"activation_alpha", {"optional_parameters", "Tensor*"} }, {"activation_beta", {"optional_parameters", "Tensor*"} }, {"activations", {"optional_parameters", "Tensor*"} }, {"clip", {"optional_parameters", "float"} }, {"direction", {"optional_parameters", "int"} }, {"hidden_size", {"optional_parameters", "int"} }, {"linear_before_reset", {"optional_parameters", "int"} }} }, 
{ "GlobalLpPool", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"p", {"optional_parameters", "int"} }} }, 
{ "Greater", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "HardSigmoid", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"alpha", {"optional_parameters", "float"} }, {"beta", {"optional_parameters", "float"} }} }, 
{ "Selu", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"alpha", {"optional_parameters", "float"} }, {"gamma", {"optional_parameters", "float"} }} }, 
{ "Hardmax", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }} }, 
{ "If", {{"cond_input", {"inputs", "Tensor*"} }, {"else_branch", {"parameters", "int"} }, {"then_branch", {"parameters", "int"} }} }, 
{ "Min", {{"min_output", {"outputs", "Tensor*"} }} }, 
{ "InstanceNormalization", {{"input_input", {"inputs", "Tensor*"} }, {"scale_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"epsilon", {"optional_parameters", "float"} }} }, 
{ "Less", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "EyeLike", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"dtype", {"optional_parameters", "int"} }, {"k", {"optional_parameters", "int"} }} }, 
{ "RandomNormal", {{"output_output", {"outputs", "Tensor*"} }, {"shape", {"parameters", "Shape_t"} }, {"dtype", {"optional_parameters", "int"} }, {"mean", {"optional_parameters", "float"} }, {"scale", {"optional_parameters", "float"} }, {"seed", {"optional_parameters", "float"} }} }, 
{ "Slice", {{"data_input", {"inputs", "Tensor*"} }, {"starts_input", {"inputs", "Tensor*"} }, {"ends_input", {"inputs", "Tensor*"} }, {"axes_input_opt", {"optional_input", "Tensor*"} }, {"steps_input_opt", {"optional_input", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "PRelu", {{"X_input", {"inputs", "Tensor*"} }, {"slope_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Log", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "LogSoftmax", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }} }, 
{ "Loop", {{"M_input_opt", {"optional_input", "Tensor*"} }, {"cond_input_opt", {"optional_input", "Tensor*"} }, {"body", {"parameters", "int"} }} }, 
{ "LpNormalization", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }, {"p", {"optional_parameters", "int"} }} }, 
{ "MatMul", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "ReduceL2", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "Max", {{"max_output", {"outputs", "Tensor*"} }} }, 
{ "MaxRoiPool", {{"X_input", {"inputs", "Tensor*"} }, {"rois_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"pooled_shape", {"parameters", "Shape_t"} }, {"spatial_scale", {"optional_parameters", "float"} }} }, 
{ "Or", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "Pad", {{"data_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"pads", {"parameters", "Shape_t"} }, {"mode", {"optional_parameters", "int"} }, {"value", {"optional_parameters", "float"} }} }, 
{ "RandomUniformLike", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"dtype", {"optional_parameters", "int"} }, {"high", {"optional_parameters", "float"} }, {"low", {"optional_parameters", "float"} }, {"seed", {"optional_parameters", "float"} }} }, 
{ "Reciprocal", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Pow", {{"X_input", {"inputs", "Tensor*"} }, {"Y_input", {"inputs", "Tensor*"} }, {"Z_output", {"outputs", "Tensor*"} }} }, 
{ "RandomNormalLike", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"dtype", {"optional_parameters", "int"} }, {"mean", {"optional_parameters", "float"} }, {"scale", {"optional_parameters", "float"} }, {"seed", {"optional_parameters", "float"} }} }, 
{ "OneHot", {{"indices_input", {"inputs", "Tensor*"} }, {"depth_input", {"inputs", "Tensor*"} }, {"values_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }} }, 
{ "RandomUniform", {{"output_output", {"outputs", "Tensor*"} }, {"shape", {"parameters", "Shape_t"} }, {"dtype", {"optional_parameters", "int"} }, {"high", {"optional_parameters", "float"} }, {"low", {"optional_parameters", "float"} }, {"seed", {"optional_parameters", "float"} }} }, 
{ "ReduceL1", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "ReduceLogSum", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "ReduceLogSumExp", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "ReduceMax", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "OneHotEncoder", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"cats_int64s", {"optional_parameters", "Shape_t"} }, {"cats_strings", {"optional_parameters", "Tensor*"} }, {"zeros", {"optional_parameters", "int"} }} }, 
{ "IsNaN", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "ReduceMean", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "ReduceMin", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "TreeEnsembleRegressor", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"aggregate_function", {"optional_parameters", "int"} }, {"base_values", {"optional_parameters", "Tensor*"} }, {"n_targets", {"optional_parameters", "int"} }, {"nodes_falsenodeids", {"optional_parameters", "Shape_t"} }, {"nodes_featureids", {"optional_parameters", "Shape_t"} }, {"nodes_hitrates", {"optional_parameters", "Tensor*"} }, {"nodes_missing_value_tracks_true", {"optional_parameters", "Shape_t"} }, {"nodes_modes", {"optional_parameters", "Tensor*"} }, {"nodes_nodeids", {"optional_parameters", "Shape_t"} }, {"nodes_treeids", {"optional_parameters", "Shape_t"} }, {"nodes_truenodeids", {"optional_parameters", "Shape_t"} }, {"nodes_values", {"optional_parameters", "Tensor*"} }, {"post_transform", {"optional_parameters", "int"} }, {"target_ids", {"optional_parameters", "Shape_t"} }, {"target_nodeids", {"optional_parameters", "Shape_t"} }, {"target_treeids", {"optional_parameters", "Shape_t"} }, {"target_weights", {"optional_parameters", "Tensor*"} }} }, 
{ "ReduceProd", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "ReduceSum", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "ReduceSumSquare", {{"data_input", {"inputs", "Tensor*"} }, {"reduced_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }, {"keepdims", {"optional_parameters", "int"} }} }, 
{ "Relu", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Reshape", {{"data_input", {"inputs", "Tensor*"} }, {"shape_input", {"inputs", "Tensor*"} }, {"reshaped_output", {"outputs", "Tensor*"} }} }, 
{ "Shape", {{"data_input", {"inputs", "Tensor*"} }, {"shape_output", {"outputs", "Tensor*"} }} }, 
{ "Sigmoid", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Size", {{"data_input", {"inputs", "Tensor*"} }, {"size_output", {"outputs", "Tensor*"} }} }, 
{ "Softmax", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }} }, 
{ "Softplus", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Softsign", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "SpaceToDepth", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"blocksize", {"parameters", "int"} }} }, 
{ "TfIdfVectorizer", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"max_gram_length", {"parameters", "int"} }, {"max_skip_count", {"parameters", "int"} }, {"min_gram_length", {"parameters", "int"} }, {"mode", {"parameters", "int"} }, {"ngram_counts", {"parameters", "Shape_t"} }, {"ngram_indexes", {"parameters", "Shape_t"} }, {"pool_int64s", {"optional_parameters", "Shape_t"} }, {"pool_strings", {"optional_parameters", "Tensor*"} }, {"weights", {"optional_parameters", "Tensor*"} }} }, 
{ "Split", {{"input_input", {"inputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }, {"split", {"optional_parameters", "Shape_t"} }} }, 
{ "Imputer", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"imputed_value_floats", {"optional_parameters", "Tensor*"} }, {"imputed_value_int64s", {"optional_parameters", "Shape_t"} }, {"replaced_value_float", {"optional_parameters", "float"} }, {"replaced_value_int64", {"optional_parameters", "int"} }} }, 
{ "Sqrt", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "Squeeze", {{"data_input", {"inputs", "Tensor*"} }, {"squeezed_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }} }, 
{ "TopK", {{"X_input", {"inputs", "Tensor*"} }, {"K_input", {"inputs", "Tensor*"} }, {"Values_output", {"outputs", "Tensor*"} }, {"Indices_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }} }, 
{ "Sub", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "Sum", {{"sum_output", {"outputs", "Tensor*"} }} }, 
{ "Shrink", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"bias", {"optional_parameters", "float"} }, {"lambd", {"optional_parameters", "float"} }} }, 
{ "Tanh", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Transpose", {{"data_input", {"inputs", "Tensor*"} }, {"transposed_output", {"outputs", "Tensor*"} }, {"perm", {"optional_parameters", "Shape_t"} }} }, 
{ "Unsqueeze", {{"data_input", {"inputs", "Tensor*"} }, {"expanded_output", {"outputs", "Tensor*"} }, {"axes", {"parameters", "Shape_t"} }} }, 
{ "SVMClassifier", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"Z_output", {"outputs", "Tensor*"} }, {"classlabels_ints", {"optional_parameters", "Shape_t"} }, {"classlabels_strings", {"optional_parameters", "Tensor*"} }, {"coefficients", {"optional_parameters", "Tensor*"} }, {"kernel_params", {"optional_parameters", "Tensor*"} }, {"kernel_type", {"optional_parameters", "int"} }, {"post_transform", {"optional_parameters", "int"} }, {"prob_a", {"optional_parameters", "Tensor*"} }, {"prob_b", {"optional_parameters", "Tensor*"} }, {"rho", {"optional_parameters", "Tensor*"} }, {"support_vectors", {"optional_parameters", "Tensor*"} }, {"vectors_per_class", {"optional_parameters", "Shape_t"} }} }, 
{ "Xor", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }} }, 
{ "Acos", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Asin", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Atan", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Cos", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Sin", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Tan", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Multinomial", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"dtype", {"optional_parameters", "int"} }, {"sample_size", {"optional_parameters", "int"} }, {"seed", {"optional_parameters", "float"} }} }, 
{ "Scan", {{"body", {"parameters", "int"} }, {"num_scan_inputs", {"parameters", "int"} }, {"scan_input_axes", {"optional_parameters", "Shape_t"} }, {"scan_input_directions", {"optional_parameters", "Shape_t"} }, {"scan_output_axes", {"optional_parameters", "Shape_t"} }, {"scan_output_directions", {"optional_parameters", "Shape_t"} }} }, 
{ "Compress", {{"input_input", {"inputs", "Tensor*"} }, {"condition_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }} }, 
{ "ConstantOfShape", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"value", {"optional_parameters", "Tensor*"} }} }, 
{ "MaxUnpool", {{"X_input", {"inputs", "Tensor*"} }, {"I_input", {"inputs", "Tensor*"} }, {"output_shape_input_opt", {"optional_input", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"kernel_shape", {"parameters", "Shape_t"} }, {"pads", {"optional_parameters", "Shape_t"} }, {"strides", {"optional_parameters", "Shape_t"} }} }, 
{ "Scatter", {{"data_input", {"inputs", "Tensor*"} }, {"indices_input", {"inputs", "Tensor*"} }, {"updates_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }, {"axis", {"optional_parameters", "int"} }} }, 
{ "Sinh", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Cosh", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Asinh", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Acosh", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "NonMaxSuppression", {{"boxes_input", {"inputs", "Tensor*"} }, {"scores_input", {"inputs", "Tensor*"} }, {"max_output_boxes_per_class_input_opt", {"optional_input", "Tensor*"} }, {"iou_threshold_input_opt", {"optional_input", "Tensor*"} }, {"score_threshold_input_opt", {"optional_input", "Tensor*"} }, {"selected_indices_output", {"outputs", "Tensor*"} }, {"center_point_box", {"optional_parameters", "int"} }} }, 
{ "Atanh", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Sign", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Erf", {{"input_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "Where", {{"condition_input", {"inputs", "Tensor*"} }, {"X_input", {"inputs", "Tensor*"} }, {"Y_input", {"inputs", "Tensor*"} }, {"output_output", {"outputs", "Tensor*"} }} }, 
{ "NonZero", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "MeanVarianceNormalization", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"axes", {"optional_parameters", "Shape_t"} }} }, 
{ "StringNormalizer", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"case_change_action", {"optional_parameters", "int"} }, {"is_case_sensitive", {"optional_parameters", "int"} }, {"locale", {"optional_parameters", "int"} }, {"stopwords", {"optional_parameters", "Tensor*"} }} }, 
{ "Mod", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"C_output", {"outputs", "Tensor*"} }, {"fmod", {"optional_parameters", "int"} }} }, 
{ "ThresholdedRelu", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"alpha", {"optional_parameters", "float"} }} }, 
{ "MatMulInteger", {{"A_input", {"inputs", "Tensor*"} }, {"B_input", {"inputs", "Tensor*"} }, {"a_zero_point_input_opt", {"optional_input", "Tensor*"} }, {"b_zero_point_input_opt", {"optional_input", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }} }, 
{ "QLinearMatMul", {{"a_input", {"inputs", "Tensor*"} }, {"a_scale_input", {"inputs", "Tensor*"} }, {"a_zero_point_input", {"inputs", "Tensor*"} }, {"b_input", {"inputs", "Tensor*"} }, {"b_scale_input", {"inputs", "Tensor*"} }, {"b_zero_point_input", {"inputs", "Tensor*"} }, {"y_scale_input", {"inputs", "Tensor*"} }, {"y_zero_point_input", {"inputs", "Tensor*"} }, {"y_output", {"outputs", "Tensor*"} }} }, 
{ "ConvInteger", {{"x_input", {"inputs", "Tensor*"} }, {"w_input", {"inputs", "Tensor*"} }, {"x_zero_point_input_opt", {"optional_input", "Tensor*"} }, {"w_zero_point_input_opt", {"optional_input", "Tensor*"} }, {"y_output", {"outputs", "Tensor*"} }, {"auto_pad", {"optional_parameters", "int"} }, {"dilations", {"optional_parameters", "Shape_t"} }, {"group", {"optional_parameters", "int"} }, {"kernel_shape", {"optional_parameters", "Shape_t"} }, {"pads", {"optional_parameters", "Shape_t"} }, {"strides", {"optional_parameters", "Shape_t"} }} }, 
{ "QLinearConv", {{"x_input", {"inputs", "Tensor*"} }, {"x_scale_input", {"inputs", "Tensor*"} }, {"x_zero_point_input", {"inputs", "Tensor*"} }, {"w_input", {"inputs", "Tensor*"} }, {"w_scale_input", {"inputs", "Tensor*"} }, {"w_zero_point_input", {"inputs", "Tensor*"} }, {"y_scale_input", {"inputs", "Tensor*"} }, {"y_zero_point_input", {"inputs", "Tensor*"} }, {"B_input_opt", {"optional_input", "Tensor*"} }, {"y_output", {"outputs", "Tensor*"} }, {"auto_pad", {"optional_parameters", "int"} }, {"dilations", {"optional_parameters", "Shape_t"} }, {"group", {"optional_parameters", "int"} }, {"kernel_shape", {"optional_parameters", "Shape_t"} }, {"pads", {"optional_parameters", "Shape_t"} }, {"strides", {"optional_parameters", "Shape_t"} }} }, 
{ "QuantizeLinear", {{"x_input", {"inputs", "Tensor*"} }, {"y_scale_input", {"inputs", "Tensor*"} }, {"y_zero_point_input_opt", {"optional_input", "Tensor*"} }, {"y_output", {"outputs", "Tensor*"} }} }, 
{ "DequantizeLinear", {{"x_input", {"inputs", "Tensor*"} }, {"x_scale_input", {"inputs", "Tensor*"} }, {"x_zero_point_input_opt", {"optional_input", "Tensor*"} }, {"y_output", {"outputs", "Tensor*"} }} }, 
{ "IsInf", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"detect_negative", {"optional_parameters", "int"} }, {"detect_positive", {"optional_parameters", "int"} }} }, 
{ "RoiAlign", {{"X_input", {"inputs", "Tensor*"} }, {"rois_input", {"inputs", "Tensor*"} }, {"batch_indices_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"mode", {"optional_parameters", "int"} }, {"output_height", {"optional_parameters", "int"} }, {"output_width", {"optional_parameters", "int"} }, {"sampling_ratio", {"optional_parameters", "int"} }, {"spatial_scale", {"optional_parameters", "float"} }} }, 
{ "ArrayFeatureExtractor", {{"X_input", {"inputs", "Tensor*"} }, {"Y_input", {"inputs", "Tensor*"} }, {"Z_output", {"outputs", "Tensor*"} }} }, 
{ "Binarizer", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"threshold", {"optional_parameters", "float"} }} }, 
{ "CategoryMapper", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"cats_int64s", {"optional_parameters", "Shape_t"} }, {"cats_strings", {"optional_parameters", "Tensor*"} }, {"default_int64", {"optional_parameters", "int"} }, {"default_string", {"optional_parameters", "int"} }} }, 
{ "DictVectorizer", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"int64_vocabulary", {"optional_parameters", "Shape_t"} }, {"string_vocabulary", {"optional_parameters", "Tensor*"} }} }, 
{ "FeatureVectorizer", {{"Y_output", {"outputs", "Tensor*"} }, {"inputdimensions", {"optional_parameters", "Shape_t"} }} }, 
{ "LabelEncoder", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"default_float", {"optional_parameters", "float"} }, {"default_int64", {"optional_parameters", "int"} }, {"default_string", {"optional_parameters", "int"} }, {"keys_floats", {"optional_parameters", "Tensor*"} }, {"keys_int64s", {"optional_parameters", "Shape_t"} }, {"keys_strings", {"optional_parameters", "Tensor*"} }, {"values_floats", {"optional_parameters", "Tensor*"} }, {"values_int64s", {"optional_parameters", "Shape_t"} }, {"values_strings", {"optional_parameters", "Tensor*"} }} }, 
{ "LinearClassifier", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"Z_output", {"outputs", "Tensor*"} }, {"coefficients", {"parameters", "Tensor*"} }, {"classlabels_ints", {"optional_parameters", "Shape_t"} }, {"classlabels_strings", {"optional_parameters", "Tensor*"} }, {"intercepts", {"optional_parameters", "Tensor*"} }, {"multi_class", {"optional_parameters", "int"} }, {"post_transform", {"optional_parameters", "int"} }} }, 
{ "LinearRegressor", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"coefficients", {"optional_parameters", "Tensor*"} }, {"intercepts", {"optional_parameters", "Tensor*"} }, {"post_transform", {"optional_parameters", "int"} }, {"targets", {"optional_parameters", "int"} }} }, 
{ "Normalizer", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"norm", {"optional_parameters", "int"} }} }, 
{ "SVMRegressor", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"coefficients", {"optional_parameters", "Tensor*"} }, {"kernel_params", {"optional_parameters", "Tensor*"} }, {"kernel_type", {"optional_parameters", "int"} }, {"n_supports", {"optional_parameters", "int"} }, {"one_class", {"optional_parameters", "int"} }, {"post_transform", {"optional_parameters", "int"} }, {"rho", {"optional_parameters", "Tensor*"} }, {"support_vectors", {"optional_parameters", "Tensor*"} }} }, 
{ "Scaler", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"offset", {"optional_parameters", "Tensor*"} }, {"scale", {"optional_parameters", "Tensor*"} }} }, 
{ "TreeEnsembleClassifier", {{"X_input", {"inputs", "Tensor*"} }, {"Y_output", {"outputs", "Tensor*"} }, {"Z_output", {"outputs", "Tensor*"} }, {"base_values", {"optional_parameters", "Tensor*"} }, {"class_ids", {"optional_parameters", "Shape_t"} }, {"class_nodeids", {"optional_parameters", "Shape_t"} }, {"class_treeids", {"optional_parameters", "Shape_t"} }, {"class_weights", {"optional_parameters", "Tensor*"} }, {"classlabels_int64s", {"optional_parameters", "Shape_t"} }, {"classlabels_strings", {"optional_parameters", "Tensor*"} }, {"nodes_falsenodeids", {"optional_parameters", "Shape_t"} }, {"nodes_featureids", {"optional_parameters", "Shape_t"} }, {"nodes_hitrates", {"optional_parameters", "Tensor*"} }, {"nodes_missing_value_tracks_true", {"optional_parameters", "Shape_t"} }, {"nodes_modes", {"optional_parameters", "Tensor*"} }, {"nodes_nodeids", {"optional_parameters", "Shape_t"} }, {"nodes_treeids", {"optional_parameters", "Shape_t"} }, {"nodes_truenodeids", {"optional_parameters", "Shape_t"} }, {"nodes_values", {"optional_parameters", "Tensor*"} }, {"post_transform", {"optional_parameters", "int"} }} }, 
{ "ZipMap", {{"X_input", {"inputs", "Tensor*"} }, {"Z_output", {"outputs", "Tensor*"} }, {"classlabels_int64s", {"optional_parameters", "Shape_t"} }, {"classlabels_strings", {"optional_parameters", "Tensor*"} }} }
*/
};

}
    