#include <map>
#include "layers.h"
namespace backend {template<typename T> Layer* createInstance(std::string n, std::vector<std::string> i, std::vector<std::string> o, std::map<std::string, std::vector<std::string>> a) { return new T(n, i, o, a); }

std::map<std::string, Layer*(*)(std::string n, std::vector<std::string> i, std::vector<std::string> o, std::map<std::string, std::vector<std::string>> a)> layer_map = {
	{ "LSTM", &createInstance<LSTM>}, 
	{ "Identity", &createInstance<Identity>}, 
	{ "Abs", &createInstance<Abs>}, 
	{ "BatchNormalization", &createInstance<BatchNormalization>}, 
	{ "Mean", &createInstance<Mean>}, 
	{ "Add", &createInstance<Add>}, 
	{ "GlobalMaxPool", &createInstance<GlobalMaxPool>}, 
	{ "Cast", &createInstance<Cast>}, 
	{ "AveragePool", &createInstance<AveragePool>}, 
	{ "And", &createInstance<And>}, 
	{ "LRN", &createInstance<LRN>}, 
	{ "ArgMax", &createInstance<ArgMax>}, 
	{ "Resize", &createInstance<Resize>}, 
	{ "Expand", &createInstance<Expand>}, 
	{ "Neg", &createInstance<Neg>}, 
	{ "Mul", &createInstance<Mul>}, 
	{ "ArgMin", &createInstance<ArgMin>}, 
	{ "CastMap", &createInstance<CastMap>}, 
	{ "Exp", &createInstance<Exp>}, 
	{ "Div", &createInstance<Div>}, 
	{ "ReverseSequence", &createInstance<ReverseSequence>}, 
	{ "Ceil", &createInstance<Ceil>}, 
	{ "DepthToSpace", &createInstance<DepthToSpace>}, 
	{ "Clip", &createInstance<Clip>}, 
	{ "RNN", &createInstance<RNN>}, 
	{ "Concat", &createInstance<Concat>}, 
	{ "Constant", &createInstance<Constant>}, 
	{ "LpPool", &createInstance<LpPool>}, 
	{ "Conv", &createInstance<Conv>}, 
	{ "Not", &createInstance<Not>}, 
	{ "Gather", &createInstance<Gather>}, 
	{ "ConvTranspose", &createInstance<ConvTranspose>}, 
	{ "Dropout", &createInstance<Dropout>}, 
	{ "LeakyRelu", &createInstance<LeakyRelu>}, 
	{ "Elu", &createInstance<Elu>}, 
	{ "GlobalAveragePool", &createInstance<GlobalAveragePool>}, 
	{ "Gemm", &createInstance<Gemm>}, 
	{ "MaxPool", &createInstance<MaxPool>}, 
	{ "Equal", &createInstance<Equal>}, 
	{ "Tile", &createInstance<Tile>}, 
	{ "Flatten", &createInstance<Flatten>}, 
	{ "Floor", &createInstance<Floor>}, 
	{ "GRU", &createInstance<GRU>}, 
	{ "GlobalLpPool", &createInstance<GlobalLpPool>}, 
	{ "Greater", &createInstance<Greater>}, 
	{ "HardSigmoid", &createInstance<HardSigmoid>}, 
	{ "Selu", &createInstance<Selu>}, 
	{ "Hardmax", &createInstance<Hardmax>}, 
	{ "If", &createInstance<If>}, 
	{ "Min", &createInstance<Min>}, 
	{ "InstanceNormalization", &createInstance<InstanceNormalization>}, 
	{ "Less", &createInstance<Less>}, 
	{ "EyeLike", &createInstance<EyeLike>}, 
	{ "RandomNormal", &createInstance<RandomNormal>}, 
	{ "Slice", &createInstance<Slice>}, 
	{ "PRelu", &createInstance<PRelu>}, 
	{ "Log", &createInstance<Log>}, 
	{ "LogSoftmax", &createInstance<LogSoftmax>}, 
	{ "Loop", &createInstance<Loop>}, 
	{ "LpNormalization", &createInstance<LpNormalization>}, 
	{ "MatMul", &createInstance<MatMul>}, 
	{ "ReduceL2", &createInstance<ReduceL2>}, 
	{ "Max", &createInstance<Max>}, 
	{ "MaxRoiPool", &createInstance<MaxRoiPool>}, 
	{ "Or", &createInstance<Or>}, 
	{ "Pad", &createInstance<Pad>}, 
	{ "RandomUniformLike", &createInstance<RandomUniformLike>}, 
	{ "Reciprocal", &createInstance<Reciprocal>}, 
	{ "Pow", &createInstance<Pow>}, 
	{ "RandomNormalLike", &createInstance<RandomNormalLike>}, 
	{ "OneHot", &createInstance<OneHot>}, 
	{ "RandomUniform", &createInstance<RandomUniform>}, 
	{ "ReduceL1", &createInstance<ReduceL1>}, 
	{ "ReduceLogSum", &createInstance<ReduceLogSum>}, 
	{ "ReduceLogSumExp", &createInstance<ReduceLogSumExp>}, 
	{ "ReduceMax", &createInstance<ReduceMax>}, 
	{ "OneHotEncoder", &createInstance<OneHotEncoder>}, 
	{ "IsNaN", &createInstance<IsNaN>}, 
	{ "ReduceMean", &createInstance<ReduceMean>}, 
	{ "ReduceMin", &createInstance<ReduceMin>}, 
	{ "TreeEnsembleRegressor", &createInstance<TreeEnsembleRegressor>}, 
	{ "ReduceProd", &createInstance<ReduceProd>}, 
	{ "ReduceSum", &createInstance<ReduceSum>}, 
	{ "ReduceSumSquare", &createInstance<ReduceSumSquare>}, 
	{ "Relu", &createInstance<Relu>}, 
	{ "Reshape", &createInstance<Reshape>}, 
	{ "Shape", &createInstance<Shape>}, 
	{ "Sigmoid", &createInstance<Sigmoid>}, 
	{ "Size", &createInstance<Size>}, 
	{ "Softmax", &createInstance<Softmax>}, 
	{ "Softplus", &createInstance<Softplus>}, 
	{ "Softsign", &createInstance<Softsign>}, 
	{ "SpaceToDepth", &createInstance<SpaceToDepth>}, 
	{ "TfIdfVectorizer", &createInstance<TfIdfVectorizer>}, 
	{ "Split", &createInstance<Split>}, 
	{ "Imputer", &createInstance<Imputer>}, 
	{ "Sqrt", &createInstance<Sqrt>}, 
	{ "Squeeze", &createInstance<Squeeze>}, 
	{ "TopK", &createInstance<TopK>}, 
	{ "Sub", &createInstance<Sub>}, 
	{ "Sum", &createInstance<Sum>}, 
	{ "Shrink", &createInstance<Shrink>}, 
	{ "Tanh", &createInstance<Tanh>}, 
	{ "Transpose", &createInstance<Transpose>}, 
	{ "Unsqueeze", &createInstance<Unsqueeze>}, 
	{ "SVMClassifier", &createInstance<SVMClassifier>}, 
	{ "Xor", &createInstance<Xor>}, 
	{ "Acos", &createInstance<Acos>}, 
	{ "Asin", &createInstance<Asin>}, 
	{ "Atan", &createInstance<Atan>}, 
	{ "Cos", &createInstance<Cos>}, 
	{ "Sin", &createInstance<Sin>}, 
	{ "Tan", &createInstance<Tan>}, 
	{ "Multinomial", &createInstance<Multinomial>}, 
	{ "Scan", &createInstance<Scan>}, 
	{ "Compress", &createInstance<Compress>}, 
	{ "ConstantOfShape", &createInstance<ConstantOfShape>}, 
	{ "MaxUnpool", &createInstance<MaxUnpool>}, 
	{ "Scatter", &createInstance<Scatter>}, 
	{ "Sinh", &createInstance<Sinh>}, 
	{ "Cosh", &createInstance<Cosh>}, 
	{ "Asinh", &createInstance<Asinh>}, 
	{ "Acosh", &createInstance<Acosh>}, 
	{ "NonMaxSuppression", &createInstance<NonMaxSuppression>}, 
	{ "Atanh", &createInstance<Atanh>}, 
	{ "Sign", &createInstance<Sign>}, 
	{ "Erf", &createInstance<Erf>}, 
	{ "Where", &createInstance<Where>}, 
	{ "NonZero", &createInstance<NonZero>}, 
	{ "MeanVarianceNormalization", &createInstance<MeanVarianceNormalization>}, 
	{ "StringNormalizer", &createInstance<StringNormalizer>}, 
	{ "Mod", &createInstance<Mod>}, 
	{ "ThresholdedRelu", &createInstance<ThresholdedRelu>}, 
	{ "MatMulInteger", &createInstance<MatMulInteger>}, 
	{ "QLinearMatMul", &createInstance<QLinearMatMul>}, 
	{ "ConvInteger", &createInstance<ConvInteger>}, 
	{ "QLinearConv", &createInstance<QLinearConv>}, 
	{ "QuantizeLinear", &createInstance<QuantizeLinear>}, 
	{ "DequantizeLinear", &createInstance<DequantizeLinear>}, 
	{ "IsInf", &createInstance<IsInf>}, 
	{ "RoiAlign", &createInstance<RoiAlign>}, 
	{ "ArrayFeatureExtractor", &createInstance<ArrayFeatureExtractor>}, 
	{ "Binarizer", &createInstance<Binarizer>}, 
	{ "CategoryMapper", &createInstance<CategoryMapper>}, 
	{ "DictVectorizer", &createInstance<DictVectorizer>}, 
	{ "FeatureVectorizer", &createInstance<FeatureVectorizer>}, 
	{ "LabelEncoder", &createInstance<LabelEncoder>}, 
	{ "LinearClassifier", &createInstance<LinearClassifier>}, 
	{ "LinearRegressor", &createInstance<LinearRegressor>}, 
	{ "Normalizer", &createInstance<Normalizer>}, 
	{ "SVMRegressor", &createInstance<SVMRegressor>}, 
	{ "Scaler", &createInstance<Scaler>}, 
	{ "TreeEnsembleClassifier", &createInstance<TreeEnsembleClassifier>}, 
	{ "ZipMap", &createInstance<ZipMap>}
};


 std::map<std::string, std::map<std::string, std::string> > parameter_map = {
{ "LSTM", {{"X", "inputs"}, {"W", "inputs"}, {"R", "inputs"}, {"B", "optional_input"}, {"sequence_lens", "optional_input"}, {"initial_h", "optional_input"}, {"initial_c", "optional_input"}, {"P", "optional_input"}, {"Y", "optional_output"}, {"Y_h", "optional_output"}, {"Y_c", "optional_output"}, {"activation_alpha", "optional_parameters"}, {"activation_beta", "optional_parameters"}, {"activations", "optional_parameters"}, {"clip", "optional_parameters"}, {"direction", "optional_parameters"}, {"hidden_size", "optional_parameters"}, {"input_forget", "optional_parameters"}} }, 
{ "Identity", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Abs", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "BatchNormalization", {{"X", "inputs"}, {"scale", "inputs"}, {"B", "inputs"}, {"mean", "inputs"}, {"var", "inputs"}, {"Y", "outputs"}, {"mean", "optional_output"}, {"var", "optional_output"}, {"saved_mean", "optional_output"}, {"saved_var", "optional_output"}, {"epsilon", "optional_parameters"}, {"momentum", "optional_parameters"}} }, 
{ "Mean", {{"mean", "outputs"}} }, 
{ "Add", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "GlobalMaxPool", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "Cast", {{"input", "inputs"}, {"output", "outputs"}, {"to", "parameters"}} }, 
{ "AveragePool", {{"X", "inputs"}, {"Y", "outputs"}, {"kernel_shape", "parameters"}, {"auto_pad", "optional_parameters"}, {"ceil_mode", "optional_parameters"}, {"count_include_pad", "optional_parameters"}, {"pads", "optional_parameters"}, {"strides", "optional_parameters"}} }, 
{ "And", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "LRN", {{"X", "inputs"}, {"Y", "outputs"}, {"size", "parameters"}, {"alpha", "optional_parameters"}, {"beta", "optional_parameters"}, {"bias", "optional_parameters"}} }, 
{ "ArgMax", {{"data", "inputs"}, {"reduced", "outputs"}, {"axis", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "Resize", {{"X", "inputs"}, {"scales", "inputs"}, {"Y", "outputs"}, {"mode", "optional_parameters"}} }, 
{ "Expand", {{"input", "inputs"}, {"shape", "inputs"}, {"output", "outputs"}} }, 
{ "Neg", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "Mul", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "ArgMin", {{"data", "inputs"}, {"reduced", "outputs"}, {"axis", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "CastMap", {{"X", "inputs"}, {"Y", "outputs"}, {"cast_to", "optional_parameters"}, {"map_form", "optional_parameters"}, {"max_map", "optional_parameters"}} }, 
{ "Exp", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Div", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "ReverseSequence", {{"input", "inputs"}, {"sequence_lens", "inputs"}, {"Y", "outputs"}, {"batch_axis", "optional_parameters"}, {"time_axis", "optional_parameters"}} }, 
{ "Ceil", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "DepthToSpace", {{"input", "inputs"}, {"output", "outputs"}, {"blocksize", "parameters"}} }, 
{ "Clip", {{"input", "inputs"}, {"output", "outputs"}, {"max", "optional_parameters"}, {"min", "optional_parameters"}} }, 
{ "RNN", {{"X", "inputs"}, {"W", "inputs"}, {"R", "inputs"}, {"B", "optional_input"}, {"sequence_lens", "optional_input"}, {"initial_h", "optional_input"}, {"Y", "optional_output"}, {"Y_h", "optional_output"}, {"activation_alpha", "optional_parameters"}, {"activation_beta", "optional_parameters"}, {"activations", "optional_parameters"}, {"clip", "optional_parameters"}, {"direction", "optional_parameters"}, {"hidden_size", "optional_parameters"}} }, 
{ "Concat", {{"concat_result", "outputs"}, {"axis", "parameters"}} }, 
{ "Constant", {{"output", "outputs"}, {"value", "parameters"}} }, 
{ "LpPool", {{"X", "inputs"}, {"Y", "outputs"}, {"kernel_shape", "parameters"}, {"auto_pad", "optional_parameters"}, {"p", "optional_parameters"}, {"pads", "optional_parameters"}, {"strides", "optional_parameters"}} }, 
{ "Conv", {{"X", "inputs"}, {"W", "inputs"}, {"B", "optional_input"}, {"Y", "outputs"}, {"auto_pad", "optional_parameters"}, {"dilations", "optional_parameters"}, {"group", "optional_parameters"}, {"kernel_shape", "optional_parameters"}, {"pads", "optional_parameters"}, {"strides", "optional_parameters"}} }, 
{ "Not", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "Gather", {{"data", "inputs"}, {"indices", "inputs"}, {"output", "outputs"}, {"axis", "optional_parameters"}} }, 
{ "ConvTranspose", {{"X", "inputs"}, {"W", "inputs"}, {"B", "optional_input"}, {"Y", "outputs"}, {"auto_pad", "optional_parameters"}, {"dilations", "optional_parameters"}, {"group", "optional_parameters"}, {"kernel_shape", "optional_parameters"}, {"output_padding", "optional_parameters"}, {"output_shape", "optional_parameters"}, {"pads", "optional_parameters"}, {"strides", "optional_parameters"}} }, 
{ "Dropout", {{"data", "inputs"}, {"output", "outputs"}, {"mask", "optional_output"}, {"ratio", "optional_parameters"}} }, 
{ "LeakyRelu", {{"X", "inputs"}, {"Y", "outputs"}, {"alpha", "optional_parameters"}} }, 
{ "Elu", {{"X", "inputs"}, {"Y", "outputs"}, {"alpha", "optional_parameters"}} }, 
{ "GlobalAveragePool", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "Gemm", {{"A", "inputs"}, {"B", "inputs"}, {"C", "inputs"}, {"Y", "outputs"}, {"alpha", "optional_parameters"}, {"beta", "optional_parameters"}, {"transA", "optional_parameters"}, {"transB", "optional_parameters"}} }, 
{ "MaxPool", {{"X", "inputs"}, {"Y", "outputs"}, {"Indices", "optional_output"}, {"kernel_shape", "parameters"}, {"auto_pad", "optional_parameters"}, {"ceil_mode", "optional_parameters"}, {"dilations", "optional_parameters"}, {"pads", "optional_parameters"}, {"storage_order", "optional_parameters"}, {"strides", "optional_parameters"}} }, 
{ "Equal", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "Tile", {{"input", "inputs"}, {"repeats", "inputs"}, {"output", "outputs"}} }, 
{ "Flatten", {{"input", "inputs"}, {"output", "outputs"}, {"axis", "optional_parameters"}} }, 
{ "Floor", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "GRU", {{"X", "inputs"}, {"W", "inputs"}, {"R", "inputs"}, {"B", "optional_input"}, {"sequence_lens", "optional_input"}, {"initial_h", "optional_input"}, {"Y", "optional_output"}, {"Y_h", "optional_output"}, {"activation_alpha", "optional_parameters"}, {"activation_beta", "optional_parameters"}, {"activations", "optional_parameters"}, {"clip", "optional_parameters"}, {"direction", "optional_parameters"}, {"hidden_size", "optional_parameters"}, {"linear_before_reset", "optional_parameters"}} }, 
{ "GlobalLpPool", {{"X", "inputs"}, {"Y", "outputs"}, {"p", "optional_parameters"}} }, 
{ "Greater", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "HardSigmoid", {{"X", "inputs"}, {"Y", "outputs"}, {"alpha", "optional_parameters"}, {"beta", "optional_parameters"}} }, 
{ "Selu", {{"X", "inputs"}, {"Y", "outputs"}, {"alpha", "optional_parameters"}, {"gamma", "optional_parameters"}} }, 
{ "Hardmax", {{"input", "inputs"}, {"output", "outputs"}, {"axis", "optional_parameters"}} }, 
{ "If", {{"cond", "inputs"}, {"else_branch", "parameters"}, {"then_branch", "parameters"}} }, 
{ "Min", {{"min", "outputs"}} }, 
{ "InstanceNormalization", {{"input", "inputs"}, {"scale", "inputs"}, {"B", "inputs"}, {"output", "outputs"}, {"epsilon", "optional_parameters"}} }, 
{ "Less", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "EyeLike", {{"input", "inputs"}, {"output", "outputs"}, {"dtype", "optional_parameters"}, {"k", "optional_parameters"}} }, 
{ "RandomNormal", {{"output", "outputs"}, {"shape", "parameters"}, {"dtype", "optional_parameters"}, {"mean", "optional_parameters"}, {"scale", "optional_parameters"}, {"seed", "optional_parameters"}} }, 
{ "Slice", {{"data", "inputs"}, {"starts", "inputs"}, {"ends", "inputs"}, {"axes", "optional_input"}, {"steps", "optional_input"}, {"output", "outputs"}} }, 
{ "PRelu", {{"X", "inputs"}, {"slope", "inputs"}, {"Y", "outputs"}} }, 
{ "Log", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "LogSoftmax", {{"input", "inputs"}, {"output", "outputs"}, {"axis", "optional_parameters"}} }, 
{ "Loop", {{"M", "optional_input"}, {"cond", "optional_input"}, {"body", "parameters"}} }, 
{ "LpNormalization", {{"input", "inputs"}, {"output", "outputs"}, {"axis", "optional_parameters"}, {"p", "optional_parameters"}} }, 
{ "MatMul", {{"A", "inputs"}, {"B", "inputs"}, {"Y", "outputs"}} }, 
{ "ReduceL2", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "Max", {{"max", "outputs"}} }, 
{ "MaxRoiPool", {{"X", "inputs"}, {"rois", "inputs"}, {"Y", "outputs"}, {"pooled_shape", "parameters"}, {"spatial_scale", "optional_parameters"}} }, 
{ "Or", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "Pad", {{"data", "inputs"}, {"output", "outputs"}, {"pads", "parameters"}, {"mode", "optional_parameters"}, {"value", "optional_parameters"}} }, 
{ "RandomUniformLike", {{"input", "inputs"}, {"output", "outputs"}, {"dtype", "optional_parameters"}, {"high", "optional_parameters"}, {"low", "optional_parameters"}, {"seed", "optional_parameters"}} }, 
{ "Reciprocal", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "Pow", {{"X", "inputs"}, {"Y", "inputs"}, {"Z", "outputs"}} }, 
{ "RandomNormalLike", {{"input", "inputs"}, {"output", "outputs"}, {"dtype", "optional_parameters"}, {"mean", "optional_parameters"}, {"scale", "optional_parameters"}, {"seed", "optional_parameters"}} }, 
{ "OneHot", {{"indices", "inputs"}, {"depth", "inputs"}, {"values", "inputs"}, {"output", "outputs"}, {"axis", "optional_parameters"}} }, 
{ "RandomUniform", {{"output", "outputs"}, {"shape", "parameters"}, {"dtype", "optional_parameters"}, {"high", "optional_parameters"}, {"low", "optional_parameters"}, {"seed", "optional_parameters"}} }, 
{ "ReduceL1", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "ReduceLogSum", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "ReduceLogSumExp", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "ReduceMax", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "OneHotEncoder", {{"X", "inputs"}, {"Y", "outputs"}, {"cats_int64s", "optional_parameters"}, {"cats_strings", "optional_parameters"}, {"zeros", "optional_parameters"}} }, 
{ "IsNaN", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "ReduceMean", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "ReduceMin", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "TreeEnsembleRegressor", {{"X", "inputs"}, {"Y", "outputs"}, {"aggregate_function", "optional_parameters"}, {"base_values", "optional_parameters"}, {"n_targets", "optional_parameters"}, {"nodes_falsenodeids", "optional_parameters"}, {"nodes_featureids", "optional_parameters"}, {"nodes_hitrates", "optional_parameters"}, {"nodes_missing_value_tracks_true", "optional_parameters"}, {"nodes_modes", "optional_parameters"}, {"nodes_nodeids", "optional_parameters"}, {"nodes_treeids", "optional_parameters"}, {"nodes_truenodeids", "optional_parameters"}, {"nodes_values", "optional_parameters"}, {"post_transform", "optional_parameters"}, {"target_ids", "optional_parameters"}, {"target_nodeids", "optional_parameters"}, {"target_treeids", "optional_parameters"}, {"target_weights", "optional_parameters"}} }, 
{ "ReduceProd", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "ReduceSum", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "ReduceSumSquare", {{"data", "inputs"}, {"reduced", "outputs"}, {"axes", "optional_parameters"}, {"keepdims", "optional_parameters"}} }, 
{ "Relu", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "Reshape", {{"data", "inputs"}, {"shape", "inputs"}, {"reshaped", "outputs"}} }, 
{ "Shape", {{"data", "inputs"}, {"shape", "outputs"}} }, 
{ "Sigmoid", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "Size", {{"data", "inputs"}, {"size", "outputs"}} }, 
{ "Softmax", {{"input", "inputs"}, {"output", "outputs"}, {"axis", "optional_parameters"}} }, 
{ "Softplus", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "Softsign", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "SpaceToDepth", {{"input", "inputs"}, {"output", "outputs"}, {"blocksize", "parameters"}} }, 
{ "TfIdfVectorizer", {{"X", "inputs"}, {"Y", "outputs"}, {"max_gram_length", "parameters"}, {"max_skip_count", "parameters"}, {"min_gram_length", "parameters"}, {"mode", "parameters"}, {"ngram_counts", "parameters"}, {"ngram_indexes", "parameters"}, {"pool_int64s", "optional_parameters"}, {"pool_strings", "optional_parameters"}, {"weights", "optional_parameters"}} }, 
{ "Split", {{"input", "inputs"}, {"axis", "optional_parameters"}, {"split", "optional_parameters"}} }, 
{ "Imputer", {{"X", "inputs"}, {"Y", "outputs"}, {"imputed_value_floats", "optional_parameters"}, {"imputed_value_int64s", "optional_parameters"}, {"replaced_value_float", "optional_parameters"}, {"replaced_value_int64", "optional_parameters"}} }, 
{ "Sqrt", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "Squeeze", {{"data", "inputs"}, {"squeezed", "outputs"}, {"axes", "optional_parameters"}} }, 
{ "TopK", {{"X", "inputs"}, {"K", "inputs"}, {"Values", "outputs"}, {"Indices", "outputs"}, {"axis", "optional_parameters"}} }, 
{ "Sub", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "Sum", {{"sum", "outputs"}} }, 
{ "Shrink", {{"input", "inputs"}, {"output", "outputs"}, {"bias", "optional_parameters"}, {"lambd", "optional_parameters"}} }, 
{ "Tanh", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Transpose", {{"data", "inputs"}, {"transposed", "outputs"}, {"perm", "optional_parameters"}} }, 
{ "Unsqueeze", {{"data", "inputs"}, {"expanded", "outputs"}, {"axes", "parameters"}} }, 
{ "SVMClassifier", {{"X", "inputs"}, {"Y", "outputs"}, {"Z", "outputs"}, {"classlabels_ints", "optional_parameters"}, {"classlabels_strings", "optional_parameters"}, {"coefficients", "optional_parameters"}, {"kernel_params", "optional_parameters"}, {"kernel_type", "optional_parameters"}, {"post_transform", "optional_parameters"}, {"prob_a", "optional_parameters"}, {"prob_b", "optional_parameters"}, {"rho", "optional_parameters"}, {"support_vectors", "optional_parameters"}, {"vectors_per_class", "optional_parameters"}} }, 
{ "Xor", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}} }, 
{ "Acos", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Asin", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Atan", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Cos", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Sin", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Tan", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Multinomial", {{"input", "inputs"}, {"output", "outputs"}, {"dtype", "optional_parameters"}, {"sample_size", "optional_parameters"}, {"seed", "optional_parameters"}} }, 
{ "Scan", {{"body", "parameters"}, {"num_scan_inputs", "parameters"}, {"scan_input_axes", "optional_parameters"}, {"scan_input_directions", "optional_parameters"}, {"scan_output_axes", "optional_parameters"}, {"scan_output_directions", "optional_parameters"}} }, 
{ "Compress", {{"input", "inputs"}, {"condition", "inputs"}, {"output", "outputs"}, {"axis", "optional_parameters"}} }, 
{ "ConstantOfShape", {{"input", "inputs"}, {"output", "outputs"}, {"value", "optional_parameters"}} }, 
{ "MaxUnpool", {{"X", "inputs"}, {"I", "inputs"}, {"output_shape", "optional_input"}, {"output", "outputs"}, {"kernel_shape", "parameters"}, {"pads", "optional_parameters"}, {"strides", "optional_parameters"}} }, 
{ "Scatter", {{"data", "inputs"}, {"indices", "inputs"}, {"updates", "inputs"}, {"output", "outputs"}, {"axis", "optional_parameters"}} }, 
{ "Sinh", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Cosh", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Asinh", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Acosh", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "NonMaxSuppression", {{"boxes", "inputs"}, {"scores", "inputs"}, {"max_output_boxes_per_class", "optional_input"}, {"iou_threshold", "optional_input"}, {"score_threshold", "optional_input"}, {"selected_indices", "outputs"}, {"center_point_box", "optional_parameters"}} }, 
{ "Atanh", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Sign", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Erf", {{"input", "inputs"}, {"output", "outputs"}} }, 
{ "Where", {{"condition", "inputs"}, {"X", "inputs"}, {"Y", "inputs"}, {"output", "outputs"}} }, 
{ "NonZero", {{"X", "inputs"}, {"Y", "outputs"}} }, 
{ "MeanVarianceNormalization", {{"X", "inputs"}, {"Y", "outputs"}, {"axes", "optional_parameters"}} }, 
{ "StringNormalizer", {{"X", "inputs"}, {"Y", "outputs"}, {"case_change_action", "optional_parameters"}, {"is_case_sensitive", "optional_parameters"}, {"locale", "optional_parameters"}, {"stopwords", "optional_parameters"}} }, 
{ "Mod", {{"A", "inputs"}, {"B", "inputs"}, {"C", "outputs"}, {"fmod", "optional_parameters"}} }, 
{ "ThresholdedRelu", {{"X", "inputs"}, {"Y", "outputs"}, {"alpha", "optional_parameters"}} }, 
{ "MatMulInteger", {{"A", "inputs"}, {"B", "inputs"}, {"a_zero_point", "optional_input"}, {"b_zero_point", "optional_input"}, {"Y", "outputs"}} }, 
{ "QLinearMatMul", {{"a", "inputs"}, {"a_scale", "inputs"}, {"a_zero_point", "inputs"}, {"b", "inputs"}, {"b_scale", "inputs"}, {"b_zero_point", "inputs"}, {"y_scale", "inputs"}, {"y_zero_point", "inputs"}, {"y", "outputs"}} }, 
{ "ConvInteger", {{"x", "inputs"}, {"w", "inputs"}, {"x_zero_point", "optional_input"}, {"w_zero_point", "optional_input"}, {"y", "outputs"}, {"auto_pad", "optional_parameters"}, {"dilations", "optional_parameters"}, {"group", "optional_parameters"}, {"kernel_shape", "optional_parameters"}, {"pads", "optional_parameters"}, {"strides", "optional_parameters"}} }, 
{ "QLinearConv", {{"x", "inputs"}, {"x_scale", "inputs"}, {"x_zero_point", "inputs"}, {"w", "inputs"}, {"w_scale", "inputs"}, {"w_zero_point", "inputs"}, {"y_scale", "inputs"}, {"y_zero_point", "inputs"}, {"B", "optional_input"}, {"y", "outputs"}, {"auto_pad", "optional_parameters"}, {"dilations", "optional_parameters"}, {"group", "optional_parameters"}, {"kernel_shape", "optional_parameters"}, {"pads", "optional_parameters"}, {"strides", "optional_parameters"}} }, 
{ "QuantizeLinear", {{"x", "inputs"}, {"y_scale", "inputs"}, {"y_zero_point", "optional_input"}, {"y", "outputs"}} }, 
{ "DequantizeLinear", {{"x", "inputs"}, {"x_scale", "inputs"}, {"x_zero_point", "optional_input"}, {"y", "outputs"}} }, 
{ "IsInf", {{"X", "inputs"}, {"Y", "outputs"}, {"detect_negative", "optional_parameters"}, {"detect_positive", "optional_parameters"}} }, 
{ "RoiAlign", {{"X", "inputs"}, {"rois", "inputs"}, {"batch_indices", "inputs"}, {"Y", "outputs"}, {"mode", "optional_parameters"}, {"output_height", "optional_parameters"}, {"output_width", "optional_parameters"}, {"sampling_ratio", "optional_parameters"}, {"spatial_scale", "optional_parameters"}} }, 
{ "ArrayFeatureExtractor", {{"X", "inputs"}, {"Y", "inputs"}, {"Z", "outputs"}} }, 
{ "Binarizer", {{"X", "inputs"}, {"Y", "outputs"}, {"threshold", "optional_parameters"}} }, 
{ "CategoryMapper", {{"X", "inputs"}, {"Y", "outputs"}, {"cats_int64s", "optional_parameters"}, {"cats_strings", "optional_parameters"}, {"default_int64", "optional_parameters"}, {"default_string", "optional_parameters"}} }, 
{ "DictVectorizer", {{"X", "inputs"}, {"Y", "outputs"}, {"int64_vocabulary", "optional_parameters"}, {"string_vocabulary", "optional_parameters"}} }, 
{ "FeatureVectorizer", {{"Y", "outputs"}, {"inputdimensions", "optional_parameters"}} }, 
{ "LabelEncoder", {{"X", "inputs"}, {"Y", "outputs"}, {"default_float", "optional_parameters"}, {"default_int64", "optional_parameters"}, {"default_string", "optional_parameters"}, {"keys_floats", "optional_parameters"}, {"keys_int64s", "optional_parameters"}, {"keys_strings", "optional_parameters"}, {"values_floats", "optional_parameters"}, {"values_int64s", "optional_parameters"}, {"values_strings", "optional_parameters"}} }, 
{ "LinearClassifier", {{"X", "inputs"}, {"Y", "outputs"}, {"Z", "outputs"}, {"coefficients", "parameters"}, {"classlabels_ints", "optional_parameters"}, {"classlabels_strings", "optional_parameters"}, {"intercepts", "optional_parameters"}, {"multi_class", "optional_parameters"}, {"post_transform", "optional_parameters"}} }, 
{ "LinearRegressor", {{"X", "inputs"}, {"Y", "outputs"}, {"coefficients", "optional_parameters"}, {"intercepts", "optional_parameters"}, {"post_transform", "optional_parameters"}, {"targets", "optional_parameters"}} }, 
{ "Normalizer", {{"X", "inputs"}, {"Y", "outputs"}, {"norm", "optional_parameters"}} }, 
{ "SVMRegressor", {{"X", "inputs"}, {"Y", "outputs"}, {"coefficients", "optional_parameters"}, {"kernel_params", "optional_parameters"}, {"kernel_type", "optional_parameters"}, {"n_supports", "optional_parameters"}, {"one_class", "optional_parameters"}, {"post_transform", "optional_parameters"}, {"rho", "optional_parameters"}, {"support_vectors", "optional_parameters"}} }, 
{ "Scaler", {{"X", "inputs"}, {"Y", "outputs"}, {"offset", "optional_parameters"}, {"scale", "optional_parameters"}} }, 
{ "TreeEnsembleClassifier", {{"X", "inputs"}, {"Y", "outputs"}, {"Z", "outputs"}, {"base_values", "optional_parameters"}, {"class_ids", "optional_parameters"}, {"class_nodeids", "optional_parameters"}, {"class_treeids", "optional_parameters"}, {"class_weights", "optional_parameters"}, {"classlabels_int64s", "optional_parameters"}, {"classlabels_strings", "optional_parameters"}, {"nodes_falsenodeids", "optional_parameters"}, {"nodes_featureids", "optional_parameters"}, {"nodes_hitrates", "optional_parameters"}, {"nodes_missing_value_tracks_true", "optional_parameters"}, {"nodes_modes", "optional_parameters"}, {"nodes_nodeids", "optional_parameters"}, {"nodes_treeids", "optional_parameters"}, {"nodes_truenodeids", "optional_parameters"}, {"nodes_values", "optional_parameters"}, {"post_transform", "optional_parameters"}} }, 
{ "ZipMap", {{"X", "inputs"}, {"Z", "outputs"}, {"classlabels_int64s", "optional_parameters"}, {"classlabels_strings", "optional_parameters"}} }
};


}
    