// Layer Shader Spv Data header
//
// This file is auto-generated by cmake, don't edit it.

static const uint32_t absval_spv_data[] = {
#include "../_spir_v/absval.spv.hex.h"
};
static const uint32_t absval_fp16p_spv_data[] = {
#include "../_spir_v/absval_fp16p.spv.hex.h"
};
static const uint32_t absval_fp16s_spv_data[] = {
#include "../_spir_v/absval_fp16s.spv.hex.h"
};
static const uint32_t absval_fp16a_spv_data[] = {
#include "../_spir_v/absval_fp16a.spv.hex.h"
};
static const uint32_t absval_pack4_spv_data[] = {
#include "../_spir_v/absval_pack4.spv.hex.h"
};
static const uint32_t absval_pack4_fp16p_spv_data[] = {
#include "../_spir_v/absval_pack4_fp16p.spv.hex.h"
};
static const uint32_t absval_pack4_fp16s_spv_data[] = {
#include "../_spir_v/absval_pack4_fp16s.spv.hex.h"
};
static const uint32_t absval_pack4_fp16a_spv_data[] = {
#include "../_spir_v/absval_pack4_fp16a.spv.hex.h"
};
static const uint32_t batchnorm_spv_data[] = {
#include "../_spir_v/batchnorm.spv.hex.h"
};
static const uint32_t batchnorm_fp16p_spv_data[] = {
#include "../_spir_v/batchnorm_fp16p.spv.hex.h"
};
static const uint32_t batchnorm_fp16s_spv_data[] = {
#include "../_spir_v/batchnorm_fp16s.spv.hex.h"
};
static const uint32_t batchnorm_fp16a_spv_data[] = {
#include "../_spir_v/batchnorm_fp16a.spv.hex.h"
};
static const uint32_t batchnorm_pack4_spv_data[] = {
#include "../_spir_v/batchnorm_pack4.spv.hex.h"
};
static const uint32_t batchnorm_pack4_fp16p_spv_data[] = {
#include "../_spir_v/batchnorm_pack4_fp16p.spv.hex.h"
};
static const uint32_t batchnorm_pack4_fp16s_spv_data[] = {
#include "../_spir_v/batchnorm_pack4_fp16s.spv.hex.h"
};
static const uint32_t batchnorm_pack4_fp16a_spv_data[] = {
#include "../_spir_v/batchnorm_pack4_fp16a.spv.hex.h"
};
static const uint32_t concat_spv_data[] = {
#include "../_spir_v/concat.spv.hex.h"
};
static const uint32_t concat_fp16p_spv_data[] = {
#include "../_spir_v/concat_fp16p.spv.hex.h"
};
static const uint32_t concat_fp16s_spv_data[] = {
#include "../_spir_v/concat_fp16s.spv.hex.h"
};
static const uint32_t concat_fp16a_spv_data[] = {
#include "../_spir_v/concat_fp16a.spv.hex.h"
};
static const uint32_t concat_pack4_spv_data[] = {
#include "../_spir_v/concat_pack4.spv.hex.h"
};
static const uint32_t concat_pack4_fp16p_spv_data[] = {
#include "../_spir_v/concat_pack4_fp16p.spv.hex.h"
};
static const uint32_t concat_pack4_fp16s_spv_data[] = {
#include "../_spir_v/concat_pack4_fp16s.spv.hex.h"
};
static const uint32_t concat_pack4_fp16a_spv_data[] = {
#include "../_spir_v/concat_pack4_fp16a.spv.hex.h"
};
static const uint32_t concat_pack4to1_spv_data[] = {
#include "../_spir_v/concat_pack4to1.spv.hex.h"
};
static const uint32_t concat_pack4to1_fp16p_spv_data[] = {
#include "../_spir_v/concat_pack4to1_fp16p.spv.hex.h"
};
static const uint32_t concat_pack4to1_fp16s_spv_data[] = {
#include "../_spir_v/concat_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t concat_pack4to1_fp16a_spv_data[] = {
#include "../_spir_v/concat_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t convolution_spv_data[] = {
#include "../_spir_v/convolution.spv.hex.h"
};
static const uint32_t convolution_fp16p_spv_data[] = {
#include "../_spir_v/convolution_fp16p.spv.hex.h"
};
static const uint32_t convolution_fp16s_spv_data[] = {
#include "../_spir_v/convolution_fp16s.spv.hex.h"
};
static const uint32_t convolution_fp16a_spv_data[] = {
#include "../_spir_v/convolution_fp16a.spv.hex.h"
};
static const uint32_t convolution_1x1s1d1_spv_data[] = {
#include "../_spir_v/convolution_1x1s1d1.spv.hex.h"
};
static const uint32_t convolution_1x1s1d1_fp16p_spv_data[] = {
#include "../_spir_v/convolution_1x1s1d1_fp16p.spv.hex.h"
};
static const uint32_t convolution_1x1s1d1_fp16s_spv_data[] = {
#include "../_spir_v/convolution_1x1s1d1_fp16s.spv.hex.h"
};
static const uint32_t convolution_1x1s1d1_fp16a_spv_data[] = {
#include "../_spir_v/convolution_1x1s1d1_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack1to4_spv_data[] = {
#include "../_spir_v/convolution_pack1to4.spv.hex.h"
};
static const uint32_t convolution_pack1to4_fp16p_spv_data[] = {
#include "../_spir_v/convolution_pack1to4_fp16p.spv.hex.h"
};
static const uint32_t convolution_pack1to4_fp16s_spv_data[] = {
#include "../_spir_v/convolution_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack1to4_fp16a_spv_data[] = {
#include "../_spir_v/convolution_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack4_spv_data[] = {
#include "../_spir_v/convolution_pack4.spv.hex.h"
};
static const uint32_t convolution_pack4_fp16p_spv_data[] = {
#include "../_spir_v/convolution_pack4_fp16p.spv.hex.h"
};
static const uint32_t convolution_pack4_fp16s_spv_data[] = {
#include "../_spir_v/convolution_pack4_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack4_fp16a_spv_data[] = {
#include "../_spir_v/convolution_pack4_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack4_1x1s1d1_spv_data[] = {
#include "../_spir_v/convolution_pack4_1x1s1d1.spv.hex.h"
};
static const uint32_t convolution_pack4_1x1s1d1_fp16p_spv_data[] = {
#include "../_spir_v/convolution_pack4_1x1s1d1_fp16p.spv.hex.h"
};
static const uint32_t convolution_pack4_1x1s1d1_fp16s_spv_data[] = {
#include "../_spir_v/convolution_pack4_1x1s1d1_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack4_1x1s1d1_fp16a_spv_data[] = {
#include "../_spir_v/convolution_pack4_1x1s1d1_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_lds_8_8_2_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_lds_8_8_2.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_lds_8_8_2_fp16p_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_lds_8_8_2_fp16p.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_lds_8_8_2_fp16s_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_lds_8_8_2_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_lds_8_8_2_fp16a_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_lds_8_8_2_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_gemm_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_gemm.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_gemm_fp16p_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_gemm_fp16p.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_gemm_fp16s_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_gemm_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_gemm_fp16a_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_gemm_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_transform_input_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_transform_input.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_transform_input_fp16p_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_transform_input_fp16p.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_transform_input_fp16s_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_transform_input_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_transform_input_fp16a_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_transform_input_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_transform_output_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_transform_output.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_transform_output_fp16p_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_transform_output_fp16p.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_transform_output_fp16s_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_transform_output_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack4_3x3s1d1_winograd23_transform_output_fp16a_spv_data[] = {
#include "../_spir_v/convolution_pack4_3x3s1d1_winograd23_transform_output_fp16a.spv.hex.h"
};
static const uint32_t convolution_pack4to1_spv_data[] = {
#include "../_spir_v/convolution_pack4to1.spv.hex.h"
};
static const uint32_t convolution_pack4to1_fp16p_spv_data[] = {
#include "../_spir_v/convolution_pack4to1_fp16p.spv.hex.h"
};
static const uint32_t convolution_pack4to1_fp16s_spv_data[] = {
#include "../_spir_v/convolution_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t convolution_pack4to1_fp16a_spv_data[] = {
#include "../_spir_v/convolution_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t crop_spv_data[] = {
#include "../_spir_v/crop.spv.hex.h"
};
static const uint32_t crop_fp16p_spv_data[] = {
#include "../_spir_v/crop_fp16p.spv.hex.h"
};
static const uint32_t crop_fp16s_spv_data[] = {
#include "../_spir_v/crop_fp16s.spv.hex.h"
};
static const uint32_t crop_fp16a_spv_data[] = {
#include "../_spir_v/crop_fp16a.spv.hex.h"
};
static const uint32_t crop_pack4_spv_data[] = {
#include "../_spir_v/crop_pack4.spv.hex.h"
};
static const uint32_t crop_pack4_fp16p_spv_data[] = {
#include "../_spir_v/crop_pack4_fp16p.spv.hex.h"
};
static const uint32_t crop_pack4_fp16s_spv_data[] = {
#include "../_spir_v/crop_pack4_fp16s.spv.hex.h"
};
static const uint32_t crop_pack4_fp16a_spv_data[] = {
#include "../_spir_v/crop_pack4_fp16a.spv.hex.h"
};
static const uint32_t deconvolution_spv_data[] = {
#include "../_spir_v/deconvolution.spv.hex.h"
};
static const uint32_t deconvolution_fp16p_spv_data[] = {
#include "../_spir_v/deconvolution_fp16p.spv.hex.h"
};
static const uint32_t deconvolution_fp16s_spv_data[] = {
#include "../_spir_v/deconvolution_fp16s.spv.hex.h"
};
static const uint32_t deconvolution_fp16a_spv_data[] = {
#include "../_spir_v/deconvolution_fp16a.spv.hex.h"
};
static const uint32_t deconvolution_pack1to4_spv_data[] = {
#include "../_spir_v/deconvolution_pack1to4.spv.hex.h"
};
static const uint32_t deconvolution_pack1to4_fp16p_spv_data[] = {
#include "../_spir_v/deconvolution_pack1to4_fp16p.spv.hex.h"
};
static const uint32_t deconvolution_pack1to4_fp16s_spv_data[] = {
#include "../_spir_v/deconvolution_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t deconvolution_pack1to4_fp16a_spv_data[] = {
#include "../_spir_v/deconvolution_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t deconvolution_pack4_spv_data[] = {
#include "../_spir_v/deconvolution_pack4.spv.hex.h"
};
static const uint32_t deconvolution_pack4_fp16p_spv_data[] = {
#include "../_spir_v/deconvolution_pack4_fp16p.spv.hex.h"
};
static const uint32_t deconvolution_pack4_fp16s_spv_data[] = {
#include "../_spir_v/deconvolution_pack4_fp16s.spv.hex.h"
};
static const uint32_t deconvolution_pack4_fp16a_spv_data[] = {
#include "../_spir_v/deconvolution_pack4_fp16a.spv.hex.h"
};
static const uint32_t deconvolution_pack4to1_spv_data[] = {
#include "../_spir_v/deconvolution_pack4to1.spv.hex.h"
};
static const uint32_t deconvolution_pack4to1_fp16p_spv_data[] = {
#include "../_spir_v/deconvolution_pack4to1_fp16p.spv.hex.h"
};
static const uint32_t deconvolution_pack4to1_fp16s_spv_data[] = {
#include "../_spir_v/deconvolution_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t deconvolution_pack4to1_fp16a_spv_data[] = {
#include "../_spir_v/deconvolution_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t dropout_spv_data[] = {
#include "../_spir_v/dropout.spv.hex.h"
};
static const uint32_t dropout_fp16p_spv_data[] = {
#include "../_spir_v/dropout_fp16p.spv.hex.h"
};
static const uint32_t dropout_fp16s_spv_data[] = {
#include "../_spir_v/dropout_fp16s.spv.hex.h"
};
static const uint32_t dropout_fp16a_spv_data[] = {
#include "../_spir_v/dropout_fp16a.spv.hex.h"
};
static const uint32_t dropout_pack4_spv_data[] = {
#include "../_spir_v/dropout_pack4.spv.hex.h"
};
static const uint32_t dropout_pack4_fp16p_spv_data[] = {
#include "../_spir_v/dropout_pack4_fp16p.spv.hex.h"
};
static const uint32_t dropout_pack4_fp16s_spv_data[] = {
#include "../_spir_v/dropout_pack4_fp16s.spv.hex.h"
};
static const uint32_t dropout_pack4_fp16a_spv_data[] = {
#include "../_spir_v/dropout_pack4_fp16a.spv.hex.h"
};
static const uint32_t eltwise_spv_data[] = {
#include "../_spir_v/eltwise.spv.hex.h"
};
static const uint32_t eltwise_fp16p_spv_data[] = {
#include "../_spir_v/eltwise_fp16p.spv.hex.h"
};
static const uint32_t eltwise_fp16s_spv_data[] = {
#include "../_spir_v/eltwise_fp16s.spv.hex.h"
};
static const uint32_t eltwise_fp16a_spv_data[] = {
#include "../_spir_v/eltwise_fp16a.spv.hex.h"
};
static const uint32_t eltwise_pack4_spv_data[] = {
#include "../_spir_v/eltwise_pack4.spv.hex.h"
};
static const uint32_t eltwise_pack4_fp16p_spv_data[] = {
#include "../_spir_v/eltwise_pack4_fp16p.spv.hex.h"
};
static const uint32_t eltwise_pack4_fp16s_spv_data[] = {
#include "../_spir_v/eltwise_pack4_fp16s.spv.hex.h"
};
static const uint32_t eltwise_pack4_fp16a_spv_data[] = {
#include "../_spir_v/eltwise_pack4_fp16a.spv.hex.h"
};
static const uint32_t flatten_spv_data[] = {
#include "../_spir_v/flatten.spv.hex.h"
};
static const uint32_t flatten_fp16p_spv_data[] = {
#include "../_spir_v/flatten_fp16p.spv.hex.h"
};
static const uint32_t flatten_fp16s_spv_data[] = {
#include "../_spir_v/flatten_fp16s.spv.hex.h"
};
static const uint32_t flatten_fp16a_spv_data[] = {
#include "../_spir_v/flatten_fp16a.spv.hex.h"
};
static const uint32_t flatten_pack1to4_spv_data[] = {
#include "../_spir_v/flatten_pack1to4.spv.hex.h"
};
static const uint32_t flatten_pack1to4_fp16p_spv_data[] = {
#include "../_spir_v/flatten_pack1to4_fp16p.spv.hex.h"
};
static const uint32_t flatten_pack1to4_fp16s_spv_data[] = {
#include "../_spir_v/flatten_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t flatten_pack1to4_fp16a_spv_data[] = {
#include "../_spir_v/flatten_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t flatten_pack4_spv_data[] = {
#include "../_spir_v/flatten_pack4.spv.hex.h"
};
static const uint32_t flatten_pack4_fp16p_spv_data[] = {
#include "../_spir_v/flatten_pack4_fp16p.spv.hex.h"
};
static const uint32_t flatten_pack4_fp16s_spv_data[] = {
#include "../_spir_v/flatten_pack4_fp16s.spv.hex.h"
};
static const uint32_t flatten_pack4_fp16a_spv_data[] = {
#include "../_spir_v/flatten_pack4_fp16a.spv.hex.h"
};
static const uint32_t innerproduct_spv_data[] = {
#include "../_spir_v/innerproduct.spv.hex.h"
};
static const uint32_t innerproduct_fp16p_spv_data[] = {
#include "../_spir_v/innerproduct_fp16p.spv.hex.h"
};
static const uint32_t innerproduct_fp16s_spv_data[] = {
#include "../_spir_v/innerproduct_fp16s.spv.hex.h"
};
static const uint32_t innerproduct_fp16a_spv_data[] = {
#include "../_spir_v/innerproduct_fp16a.spv.hex.h"
};
static const uint32_t innerproduct_pack1to4_spv_data[] = {
#include "../_spir_v/innerproduct_pack1to4.spv.hex.h"
};
static const uint32_t innerproduct_pack1to4_fp16p_spv_data[] = {
#include "../_spir_v/innerproduct_pack1to4_fp16p.spv.hex.h"
};
static const uint32_t innerproduct_pack1to4_fp16s_spv_data[] = {
#include "../_spir_v/innerproduct_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t innerproduct_pack1to4_fp16a_spv_data[] = {
#include "../_spir_v/innerproduct_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t innerproduct_pack4_spv_data[] = {
#include "../_spir_v/innerproduct_pack4.spv.hex.h"
};
static const uint32_t innerproduct_pack4_fp16p_spv_data[] = {
#include "../_spir_v/innerproduct_pack4_fp16p.spv.hex.h"
};
static const uint32_t innerproduct_pack4_fp16s_spv_data[] = {
#include "../_spir_v/innerproduct_pack4_fp16s.spv.hex.h"
};
static const uint32_t innerproduct_pack4_fp16a_spv_data[] = {
#include "../_spir_v/innerproduct_pack4_fp16a.spv.hex.h"
};
static const uint32_t innerproduct_pack4_lds_64_spv_data[] = {
#include "../_spir_v/innerproduct_pack4_lds_64.spv.hex.h"
};
static const uint32_t innerproduct_pack4_lds_64_fp16p_spv_data[] = {
#include "../_spir_v/innerproduct_pack4_lds_64_fp16p.spv.hex.h"
};
static const uint32_t innerproduct_pack4_lds_64_fp16s_spv_data[] = {
#include "../_spir_v/innerproduct_pack4_lds_64_fp16s.spv.hex.h"
};
static const uint32_t innerproduct_pack4_lds_64_fp16a_spv_data[] = {
#include "../_spir_v/innerproduct_pack4_lds_64_fp16a.spv.hex.h"
};
static const uint32_t innerproduct_pack4to1_spv_data[] = {
#include "../_spir_v/innerproduct_pack4to1.spv.hex.h"
};
static const uint32_t innerproduct_pack4to1_fp16p_spv_data[] = {
#include "../_spir_v/innerproduct_pack4to1_fp16p.spv.hex.h"
};
static const uint32_t innerproduct_pack4to1_fp16s_spv_data[] = {
#include "../_spir_v/innerproduct_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t innerproduct_pack4to1_fp16a_spv_data[] = {
#include "../_spir_v/innerproduct_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t lrn_norm_spv_data[] = {
#include "../_spir_v/lrn_norm.spv.hex.h"
};
static const uint32_t lrn_norm_fp16p_spv_data[] = {
#include "../_spir_v/lrn_norm_fp16p.spv.hex.h"
};
static const uint32_t lrn_norm_fp16s_spv_data[] = {
#include "../_spir_v/lrn_norm_fp16s.spv.hex.h"
};
static const uint32_t lrn_norm_fp16a_spv_data[] = {
#include "../_spir_v/lrn_norm_fp16a.spv.hex.h"
};
static const uint32_t lrn_norm_across_channel_pack4_spv_data[] = {
#include "../_spir_v/lrn_norm_across_channel_pack4.spv.hex.h"
};
static const uint32_t lrn_norm_across_channel_pack4_fp16p_spv_data[] = {
#include "../_spir_v/lrn_norm_across_channel_pack4_fp16p.spv.hex.h"
};
static const uint32_t lrn_norm_across_channel_pack4_fp16s_spv_data[] = {
#include "../_spir_v/lrn_norm_across_channel_pack4_fp16s.spv.hex.h"
};
static const uint32_t lrn_norm_across_channel_pack4_fp16a_spv_data[] = {
#include "../_spir_v/lrn_norm_across_channel_pack4_fp16a.spv.hex.h"
};
static const uint32_t lrn_norm_within_channel_pack4_spv_data[] = {
#include "../_spir_v/lrn_norm_within_channel_pack4.spv.hex.h"
};
static const uint32_t lrn_norm_within_channel_pack4_fp16p_spv_data[] = {
#include "../_spir_v/lrn_norm_within_channel_pack4_fp16p.spv.hex.h"
};
static const uint32_t lrn_norm_within_channel_pack4_fp16s_spv_data[] = {
#include "../_spir_v/lrn_norm_within_channel_pack4_fp16s.spv.hex.h"
};
static const uint32_t lrn_norm_within_channel_pack4_fp16a_spv_data[] = {
#include "../_spir_v/lrn_norm_within_channel_pack4_fp16a.spv.hex.h"
};
static const uint32_t lrn_square_pad_spv_data[] = {
#include "../_spir_v/lrn_square_pad.spv.hex.h"
};
static const uint32_t lrn_square_pad_fp16p_spv_data[] = {
#include "../_spir_v/lrn_square_pad_fp16p.spv.hex.h"
};
static const uint32_t lrn_square_pad_fp16s_spv_data[] = {
#include "../_spir_v/lrn_square_pad_fp16s.spv.hex.h"
};
static const uint32_t lrn_square_pad_fp16a_spv_data[] = {
#include "../_spir_v/lrn_square_pad_fp16a.spv.hex.h"
};
static const uint32_t lrn_square_pad_across_channel_pack4_spv_data[] = {
#include "../_spir_v/lrn_square_pad_across_channel_pack4.spv.hex.h"
};
static const uint32_t lrn_square_pad_across_channel_pack4_fp16p_spv_data[] = {
#include "../_spir_v/lrn_square_pad_across_channel_pack4_fp16p.spv.hex.h"
};
static const uint32_t lrn_square_pad_across_channel_pack4_fp16s_spv_data[] = {
#include "../_spir_v/lrn_square_pad_across_channel_pack4_fp16s.spv.hex.h"
};
static const uint32_t lrn_square_pad_across_channel_pack4_fp16a_spv_data[] = {
#include "../_spir_v/lrn_square_pad_across_channel_pack4_fp16a.spv.hex.h"
};
static const uint32_t lrn_square_pad_within_channel_pack4_spv_data[] = {
#include "../_spir_v/lrn_square_pad_within_channel_pack4.spv.hex.h"
};
static const uint32_t lrn_square_pad_within_channel_pack4_fp16p_spv_data[] = {
#include "../_spir_v/lrn_square_pad_within_channel_pack4_fp16p.spv.hex.h"
};
static const uint32_t lrn_square_pad_within_channel_pack4_fp16s_spv_data[] = {
#include "../_spir_v/lrn_square_pad_within_channel_pack4_fp16s.spv.hex.h"
};
static const uint32_t lrn_square_pad_within_channel_pack4_fp16a_spv_data[] = {
#include "../_spir_v/lrn_square_pad_within_channel_pack4_fp16a.spv.hex.h"
};
static const uint32_t pooling_spv_data[] = {
#include "../_spir_v/pooling.spv.hex.h"
};
static const uint32_t pooling_fp16p_spv_data[] = {
#include "../_spir_v/pooling_fp16p.spv.hex.h"
};
static const uint32_t pooling_fp16s_spv_data[] = {
#include "../_spir_v/pooling_fp16s.spv.hex.h"
};
static const uint32_t pooling_fp16a_spv_data[] = {
#include "../_spir_v/pooling_fp16a.spv.hex.h"
};
static const uint32_t pooling_global_spv_data[] = {
#include "../_spir_v/pooling_global.spv.hex.h"
};
static const uint32_t pooling_global_fp16p_spv_data[] = {
#include "../_spir_v/pooling_global_fp16p.spv.hex.h"
};
static const uint32_t pooling_global_fp16s_spv_data[] = {
#include "../_spir_v/pooling_global_fp16s.spv.hex.h"
};
static const uint32_t pooling_global_fp16a_spv_data[] = {
#include "../_spir_v/pooling_global_fp16a.spv.hex.h"
};
static const uint32_t pooling_global_pack4_spv_data[] = {
#include "../_spir_v/pooling_global_pack4.spv.hex.h"
};
static const uint32_t pooling_global_pack4_fp16p_spv_data[] = {
#include "../_spir_v/pooling_global_pack4_fp16p.spv.hex.h"
};
static const uint32_t pooling_global_pack4_fp16s_spv_data[] = {
#include "../_spir_v/pooling_global_pack4_fp16s.spv.hex.h"
};
static const uint32_t pooling_global_pack4_fp16a_spv_data[] = {
#include "../_spir_v/pooling_global_pack4_fp16a.spv.hex.h"
};
static const uint32_t pooling_pack4_spv_data[] = {
#include "../_spir_v/pooling_pack4.spv.hex.h"
};
static const uint32_t pooling_pack4_fp16p_spv_data[] = {
#include "../_spir_v/pooling_pack4_fp16p.spv.hex.h"
};
static const uint32_t pooling_pack4_fp16s_spv_data[] = {
#include "../_spir_v/pooling_pack4_fp16s.spv.hex.h"
};
static const uint32_t pooling_pack4_fp16a_spv_data[] = {
#include "../_spir_v/pooling_pack4_fp16a.spv.hex.h"
};
static const uint32_t prelu_spv_data[] = {
#include "../_spir_v/prelu.spv.hex.h"
};
static const uint32_t prelu_fp16p_spv_data[] = {
#include "../_spir_v/prelu_fp16p.spv.hex.h"
};
static const uint32_t prelu_fp16s_spv_data[] = {
#include "../_spir_v/prelu_fp16s.spv.hex.h"
};
static const uint32_t prelu_fp16a_spv_data[] = {
#include "../_spir_v/prelu_fp16a.spv.hex.h"
};
static const uint32_t prelu_pack4_spv_data[] = {
#include "../_spir_v/prelu_pack4.spv.hex.h"
};
static const uint32_t prelu_pack4_fp16p_spv_data[] = {
#include "../_spir_v/prelu_pack4_fp16p.spv.hex.h"
};
static const uint32_t prelu_pack4_fp16s_spv_data[] = {
#include "../_spir_v/prelu_pack4_fp16s.spv.hex.h"
};
static const uint32_t prelu_pack4_fp16a_spv_data[] = {
#include "../_spir_v/prelu_pack4_fp16a.spv.hex.h"
};
static const uint32_t relu_spv_data[] = {
#include "../_spir_v/relu.spv.hex.h"
};
static const uint32_t relu_fp16p_spv_data[] = {
#include "../_spir_v/relu_fp16p.spv.hex.h"
};
static const uint32_t relu_fp16s_spv_data[] = {
#include "../_spir_v/relu_fp16s.spv.hex.h"
};
static const uint32_t relu_fp16a_spv_data[] = {
#include "../_spir_v/relu_fp16a.spv.hex.h"
};
static const uint32_t relu_pack4_spv_data[] = {
#include "../_spir_v/relu_pack4.spv.hex.h"
};
static const uint32_t relu_pack4_fp16p_spv_data[] = {
#include "../_spir_v/relu_pack4_fp16p.spv.hex.h"
};
static const uint32_t relu_pack4_fp16s_spv_data[] = {
#include "../_spir_v/relu_pack4_fp16s.spv.hex.h"
};
static const uint32_t relu_pack4_fp16a_spv_data[] = {
#include "../_spir_v/relu_pack4_fp16a.spv.hex.h"
};
static const uint32_t reshape_spv_data[] = {
#include "../_spir_v/reshape.spv.hex.h"
};
static const uint32_t reshape_fp16p_spv_data[] = {
#include "../_spir_v/reshape_fp16p.spv.hex.h"
};
static const uint32_t reshape_fp16s_spv_data[] = {
#include "../_spir_v/reshape_fp16s.spv.hex.h"
};
static const uint32_t reshape_fp16a_spv_data[] = {
#include "../_spir_v/reshape_fp16a.spv.hex.h"
};
static const uint32_t reshape_pack1to4_spv_data[] = {
#include "../_spir_v/reshape_pack1to4.spv.hex.h"
};
static const uint32_t reshape_pack1to4_fp16p_spv_data[] = {
#include "../_spir_v/reshape_pack1to4_fp16p.spv.hex.h"
};
static const uint32_t reshape_pack1to4_fp16s_spv_data[] = {
#include "../_spir_v/reshape_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t reshape_pack1to4_fp16a_spv_data[] = {
#include "../_spir_v/reshape_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t reshape_pack4_spv_data[] = {
#include "../_spir_v/reshape_pack4.spv.hex.h"
};
static const uint32_t reshape_pack4_fp16p_spv_data[] = {
#include "../_spir_v/reshape_pack4_fp16p.spv.hex.h"
};
static const uint32_t reshape_pack4_fp16s_spv_data[] = {
#include "../_spir_v/reshape_pack4_fp16s.spv.hex.h"
};
static const uint32_t reshape_pack4_fp16a_spv_data[] = {
#include "../_spir_v/reshape_pack4_fp16a.spv.hex.h"
};
static const uint32_t reshape_pack4to1_spv_data[] = {
#include "../_spir_v/reshape_pack4to1.spv.hex.h"
};
static const uint32_t reshape_pack4to1_fp16p_spv_data[] = {
#include "../_spir_v/reshape_pack4to1_fp16p.spv.hex.h"
};
static const uint32_t reshape_pack4to1_fp16s_spv_data[] = {
#include "../_spir_v/reshape_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t reshape_pack4to1_fp16a_spv_data[] = {
#include "../_spir_v/reshape_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t scale_spv_data[] = {
#include "../_spir_v/scale.spv.hex.h"
};
static const uint32_t scale_fp16p_spv_data[] = {
#include "../_spir_v/scale_fp16p.spv.hex.h"
};
static const uint32_t scale_fp16s_spv_data[] = {
#include "../_spir_v/scale_fp16s.spv.hex.h"
};
static const uint32_t scale_fp16a_spv_data[] = {
#include "../_spir_v/scale_fp16a.spv.hex.h"
};
static const uint32_t scale_pack4_spv_data[] = {
#include "../_spir_v/scale_pack4.spv.hex.h"
};
static const uint32_t scale_pack4_fp16p_spv_data[] = {
#include "../_spir_v/scale_pack4_fp16p.spv.hex.h"
};
static const uint32_t scale_pack4_fp16s_spv_data[] = {
#include "../_spir_v/scale_pack4_fp16s.spv.hex.h"
};
static const uint32_t scale_pack4_fp16a_spv_data[] = {
#include "../_spir_v/scale_pack4_fp16a.spv.hex.h"
};
static const uint32_t sigmoid_spv_data[] = {
#include "../_spir_v/sigmoid.spv.hex.h"
};
static const uint32_t sigmoid_fp16p_spv_data[] = {
#include "../_spir_v/sigmoid_fp16p.spv.hex.h"
};
static const uint32_t sigmoid_fp16s_spv_data[] = {
#include "../_spir_v/sigmoid_fp16s.spv.hex.h"
};
static const uint32_t sigmoid_fp16a_spv_data[] = {
#include "../_spir_v/sigmoid_fp16a.spv.hex.h"
};
static const uint32_t sigmoid_pack4_spv_data[] = {
#include "../_spir_v/sigmoid_pack4.spv.hex.h"
};
static const uint32_t sigmoid_pack4_fp16p_spv_data[] = {
#include "../_spir_v/sigmoid_pack4_fp16p.spv.hex.h"
};
static const uint32_t sigmoid_pack4_fp16s_spv_data[] = {
#include "../_spir_v/sigmoid_pack4_fp16s.spv.hex.h"
};
static const uint32_t sigmoid_pack4_fp16a_spv_data[] = {
#include "../_spir_v/sigmoid_pack4_fp16a.spv.hex.h"
};
static const uint32_t softmax_div_sum_spv_data[] = {
#include "../_spir_v/softmax_div_sum.spv.hex.h"
};
static const uint32_t softmax_div_sum_fp16p_spv_data[] = {
#include "../_spir_v/softmax_div_sum_fp16p.spv.hex.h"
};
static const uint32_t softmax_div_sum_fp16s_spv_data[] = {
#include "../_spir_v/softmax_div_sum_fp16s.spv.hex.h"
};
static const uint32_t softmax_div_sum_fp16a_spv_data[] = {
#include "../_spir_v/softmax_div_sum_fp16a.spv.hex.h"
};
static const uint32_t softmax_div_sum_pack4_spv_data[] = {
#include "../_spir_v/softmax_div_sum_pack4.spv.hex.h"
};
static const uint32_t softmax_div_sum_pack4_fp16p_spv_data[] = {
#include "../_spir_v/softmax_div_sum_pack4_fp16p.spv.hex.h"
};
static const uint32_t softmax_div_sum_pack4_fp16s_spv_data[] = {
#include "../_spir_v/softmax_div_sum_pack4_fp16s.spv.hex.h"
};
static const uint32_t softmax_div_sum_pack4_fp16a_spv_data[] = {
#include "../_spir_v/softmax_div_sum_pack4_fp16a.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_spv_data[] = {
#include "../_spir_v/softmax_exp_sub_max.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_fp16p_spv_data[] = {
#include "../_spir_v/softmax_exp_sub_max_fp16p.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_fp16s_spv_data[] = {
#include "../_spir_v/softmax_exp_sub_max_fp16s.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_fp16a_spv_data[] = {
#include "../_spir_v/softmax_exp_sub_max_fp16a.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_pack4_spv_data[] = {
#include "../_spir_v/softmax_exp_sub_max_pack4.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_pack4_fp16p_spv_data[] = {
#include "../_spir_v/softmax_exp_sub_max_pack4_fp16p.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_pack4_fp16s_spv_data[] = {
#include "../_spir_v/softmax_exp_sub_max_pack4_fp16s.spv.hex.h"
};
static const uint32_t softmax_exp_sub_max_pack4_fp16a_spv_data[] = {
#include "../_spir_v/softmax_exp_sub_max_pack4_fp16a.spv.hex.h"
};
static const uint32_t softmax_reduce_max_spv_data[] = {
#include "../_spir_v/softmax_reduce_max.spv.hex.h"
};
static const uint32_t softmax_reduce_max_fp16p_spv_data[] = {
#include "../_spir_v/softmax_reduce_max_fp16p.spv.hex.h"
};
static const uint32_t softmax_reduce_max_fp16s_spv_data[] = {
#include "../_spir_v/softmax_reduce_max_fp16s.spv.hex.h"
};
static const uint32_t softmax_reduce_max_fp16a_spv_data[] = {
#include "../_spir_v/softmax_reduce_max_fp16a.spv.hex.h"
};
static const uint32_t softmax_reduce_max_pack4_spv_data[] = {
#include "../_spir_v/softmax_reduce_max_pack4.spv.hex.h"
};
static const uint32_t softmax_reduce_max_pack4_fp16p_spv_data[] = {
#include "../_spir_v/softmax_reduce_max_pack4_fp16p.spv.hex.h"
};
static const uint32_t softmax_reduce_max_pack4_fp16s_spv_data[] = {
#include "../_spir_v/softmax_reduce_max_pack4_fp16s.spv.hex.h"
};
static const uint32_t softmax_reduce_max_pack4_fp16a_spv_data[] = {
#include "../_spir_v/softmax_reduce_max_pack4_fp16a.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_spv_data[] = {
#include "../_spir_v/softmax_reduce_sum.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_fp16p_spv_data[] = {
#include "../_spir_v/softmax_reduce_sum_fp16p.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_fp16s_spv_data[] = {
#include "../_spir_v/softmax_reduce_sum_fp16s.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_fp16a_spv_data[] = {
#include "../_spir_v/softmax_reduce_sum_fp16a.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_pack4_spv_data[] = {
#include "../_spir_v/softmax_reduce_sum_pack4.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_pack4_fp16p_spv_data[] = {
#include "../_spir_v/softmax_reduce_sum_pack4_fp16p.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_pack4_fp16s_spv_data[] = {
#include "../_spir_v/softmax_reduce_sum_pack4_fp16s.spv.hex.h"
};
static const uint32_t softmax_reduce_sum_pack4_fp16a_spv_data[] = {
#include "../_spir_v/softmax_reduce_sum_pack4_fp16a.spv.hex.h"
};
static const uint32_t tanh_spv_data[] = {
#include "../_spir_v/tanh.spv.hex.h"
};
static const uint32_t tanh_fp16p_spv_data[] = {
#include "../_spir_v/tanh_fp16p.spv.hex.h"
};
static const uint32_t tanh_fp16s_spv_data[] = {
#include "../_spir_v/tanh_fp16s.spv.hex.h"
};
static const uint32_t tanh_fp16a_spv_data[] = {
#include "../_spir_v/tanh_fp16a.spv.hex.h"
};
static const uint32_t tanh_pack4_spv_data[] = {
#include "../_spir_v/tanh_pack4.spv.hex.h"
};
static const uint32_t tanh_pack4_fp16p_spv_data[] = {
#include "../_spir_v/tanh_pack4_fp16p.spv.hex.h"
};
static const uint32_t tanh_pack4_fp16s_spv_data[] = {
#include "../_spir_v/tanh_pack4_fp16s.spv.hex.h"
};
static const uint32_t tanh_pack4_fp16a_spv_data[] = {
#include "../_spir_v/tanh_pack4_fp16a.spv.hex.h"
};
static const uint32_t binaryop_spv_data[] = {
#include "../_spir_v/binaryop.spv.hex.h"
};
static const uint32_t binaryop_fp16p_spv_data[] = {
#include "../_spir_v/binaryop_fp16p.spv.hex.h"
};
static const uint32_t binaryop_fp16s_spv_data[] = {
#include "../_spir_v/binaryop_fp16s.spv.hex.h"
};
static const uint32_t binaryop_fp16a_spv_data[] = {
#include "../_spir_v/binaryop_fp16a.spv.hex.h"
};
static const uint32_t binaryop_pack4_spv_data[] = {
#include "../_spir_v/binaryop_pack4.spv.hex.h"
};
static const uint32_t binaryop_pack4_fp16p_spv_data[] = {
#include "../_spir_v/binaryop_pack4_fp16p.spv.hex.h"
};
static const uint32_t binaryop_pack4_fp16s_spv_data[] = {
#include "../_spir_v/binaryop_pack4_fp16s.spv.hex.h"
};
static const uint32_t binaryop_pack4_fp16a_spv_data[] = {
#include "../_spir_v/binaryop_pack4_fp16a.spv.hex.h"
};
static const uint32_t unaryop_spv_data[] = {
#include "../_spir_v/unaryop.spv.hex.h"
};
static const uint32_t unaryop_fp16p_spv_data[] = {
#include "../_spir_v/unaryop_fp16p.spv.hex.h"
};
static const uint32_t unaryop_fp16s_spv_data[] = {
#include "../_spir_v/unaryop_fp16s.spv.hex.h"
};
static const uint32_t unaryop_fp16a_spv_data[] = {
#include "../_spir_v/unaryop_fp16a.spv.hex.h"
};
static const uint32_t unaryop_pack4_spv_data[] = {
#include "../_spir_v/unaryop_pack4.spv.hex.h"
};
static const uint32_t unaryop_pack4_fp16p_spv_data[] = {
#include "../_spir_v/unaryop_pack4_fp16p.spv.hex.h"
};
static const uint32_t unaryop_pack4_fp16s_spv_data[] = {
#include "../_spir_v/unaryop_pack4_fp16s.spv.hex.h"
};
static const uint32_t unaryop_pack4_fp16a_spv_data[] = {
#include "../_spir_v/unaryop_pack4_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_spv_data[] = {
#include "../_spir_v/convolutiondepthwise.spv.hex.h"
};
static const uint32_t convolutiondepthwise_fp16p_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_fp16p.spv.hex.h"
};
static const uint32_t convolutiondepthwise_fp16s_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_fp16a_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_fp16p_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_fp16p.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_fp16s_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_fp16a_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack1to4_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack1to4.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack1to4_fp16p_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack1to4_fp16p.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack1to4_fp16s_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack1to4_fp16a_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack4.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4_fp16p_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack4_fp16p.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4_fp16s_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack4_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4_fp16a_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack4_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4to1_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack4to1.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4to1_fp16p_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack4to1_fp16p.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4to1_fp16s_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_group_pack4to1_fp16a_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_group_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t convolutiondepthwise_pack4_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_pack4.spv.hex.h"
};
static const uint32_t convolutiondepthwise_pack4_fp16p_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_pack4_fp16p.spv.hex.h"
};
static const uint32_t convolutiondepthwise_pack4_fp16s_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_pack4_fp16s.spv.hex.h"
};
static const uint32_t convolutiondepthwise_pack4_fp16a_spv_data[] = {
#include "../_spir_v/convolutiondepthwise_pack4_fp16a.spv.hex.h"
};
static const uint32_t padding_spv_data[] = {
#include "../_spir_v/padding.spv.hex.h"
};
static const uint32_t padding_fp16p_spv_data[] = {
#include "../_spir_v/padding_fp16p.spv.hex.h"
};
static const uint32_t padding_fp16s_spv_data[] = {
#include "../_spir_v/padding_fp16s.spv.hex.h"
};
static const uint32_t padding_fp16a_spv_data[] = {
#include "../_spir_v/padding_fp16a.spv.hex.h"
};
static const uint32_t padding_pack4_spv_data[] = {
#include "../_spir_v/padding_pack4.spv.hex.h"
};
static const uint32_t padding_pack4_fp16p_spv_data[] = {
#include "../_spir_v/padding_pack4_fp16p.spv.hex.h"
};
static const uint32_t padding_pack4_fp16s_spv_data[] = {
#include "../_spir_v/padding_pack4_fp16s.spv.hex.h"
};
static const uint32_t padding_pack4_fp16a_spv_data[] = {
#include "../_spir_v/padding_pack4_fp16a.spv.hex.h"
};
static const uint32_t permute_spv_data[] = {
#include "../_spir_v/permute.spv.hex.h"
};
static const uint32_t permute_fp16p_spv_data[] = {
#include "../_spir_v/permute_fp16p.spv.hex.h"
};
static const uint32_t permute_fp16s_spv_data[] = {
#include "../_spir_v/permute_fp16s.spv.hex.h"
};
static const uint32_t permute_fp16a_spv_data[] = {
#include "../_spir_v/permute_fp16a.spv.hex.h"
};
static const uint32_t permute_pack4to1_spv_data[] = {
#include "../_spir_v/permute_pack4to1.spv.hex.h"
};
static const uint32_t permute_pack4to1_fp16p_spv_data[] = {
#include "../_spir_v/permute_pack4to1_fp16p.spv.hex.h"
};
static const uint32_t permute_pack4to1_fp16s_spv_data[] = {
#include "../_spir_v/permute_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t permute_pack4to1_fp16a_spv_data[] = {
#include "../_spir_v/permute_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t priorbox_spv_data[] = {
#include "../_spir_v/priorbox.spv.hex.h"
};
static const uint32_t priorbox_fp16p_spv_data[] = {
#include "../_spir_v/priorbox_fp16p.spv.hex.h"
};
static const uint32_t priorbox_fp16s_spv_data[] = {
#include "../_spir_v/priorbox_fp16s.spv.hex.h"
};
static const uint32_t priorbox_fp16a_spv_data[] = {
#include "../_spir_v/priorbox_fp16a.spv.hex.h"
};
static const uint32_t priorbox_mxnet_spv_data[] = {
#include "../_spir_v/priorbox_mxnet.spv.hex.h"
};
static const uint32_t priorbox_mxnet_fp16p_spv_data[] = {
#include "../_spir_v/priorbox_mxnet_fp16p.spv.hex.h"
};
static const uint32_t priorbox_mxnet_fp16s_spv_data[] = {
#include "../_spir_v/priorbox_mxnet_fp16s.spv.hex.h"
};
static const uint32_t priorbox_mxnet_fp16a_spv_data[] = {
#include "../_spir_v/priorbox_mxnet_fp16a.spv.hex.h"
};
static const uint32_t interp_spv_data[] = {
#include "../_spir_v/interp.spv.hex.h"
};
static const uint32_t interp_fp16p_spv_data[] = {
#include "../_spir_v/interp_fp16p.spv.hex.h"
};
static const uint32_t interp_fp16s_spv_data[] = {
#include "../_spir_v/interp_fp16s.spv.hex.h"
};
static const uint32_t interp_fp16a_spv_data[] = {
#include "../_spir_v/interp_fp16a.spv.hex.h"
};
static const uint32_t interp_bicubic_spv_data[] = {
#include "../_spir_v/interp_bicubic.spv.hex.h"
};
static const uint32_t interp_bicubic_fp16p_spv_data[] = {
#include "../_spir_v/interp_bicubic_fp16p.spv.hex.h"
};
static const uint32_t interp_bicubic_fp16s_spv_data[] = {
#include "../_spir_v/interp_bicubic_fp16s.spv.hex.h"
};
static const uint32_t interp_bicubic_fp16a_spv_data[] = {
#include "../_spir_v/interp_bicubic_fp16a.spv.hex.h"
};
static const uint32_t interp_bicubic_coeffs_spv_data[] = {
#include "../_spir_v/interp_bicubic_coeffs.spv.hex.h"
};
static const uint32_t interp_bicubic_coeffs_fp16p_spv_data[] = {
#include "../_spir_v/interp_bicubic_coeffs_fp16p.spv.hex.h"
};
static const uint32_t interp_bicubic_coeffs_fp16s_spv_data[] = {
#include "../_spir_v/interp_bicubic_coeffs_fp16s.spv.hex.h"
};
static const uint32_t interp_bicubic_coeffs_fp16a_spv_data[] = {
#include "../_spir_v/interp_bicubic_coeffs_fp16a.spv.hex.h"
};
static const uint32_t interp_bicubic_pack4_spv_data[] = {
#include "../_spir_v/interp_bicubic_pack4.spv.hex.h"
};
static const uint32_t interp_bicubic_pack4_fp16p_spv_data[] = {
#include "../_spir_v/interp_bicubic_pack4_fp16p.spv.hex.h"
};
static const uint32_t interp_bicubic_pack4_fp16s_spv_data[] = {
#include "../_spir_v/interp_bicubic_pack4_fp16s.spv.hex.h"
};
static const uint32_t interp_bicubic_pack4_fp16a_spv_data[] = {
#include "../_spir_v/interp_bicubic_pack4_fp16a.spv.hex.h"
};
static const uint32_t interp_pack4_spv_data[] = {
#include "../_spir_v/interp_pack4.spv.hex.h"
};
static const uint32_t interp_pack4_fp16p_spv_data[] = {
#include "../_spir_v/interp_pack4_fp16p.spv.hex.h"
};
static const uint32_t interp_pack4_fp16s_spv_data[] = {
#include "../_spir_v/interp_pack4_fp16s.spv.hex.h"
};
static const uint32_t interp_pack4_fp16a_spv_data[] = {
#include "../_spir_v/interp_pack4_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_fp16p_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_fp16p.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_fp16s_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_fp16a_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_fp16p_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_fp16p.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_fp16s_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_fp16a_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack1to4_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack1to4.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack1to4_fp16p_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack1to4_fp16p.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack1to4_fp16s_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack1to4_fp16a_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack4.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4_fp16p_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack4_fp16p.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4_fp16s_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack4_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4_fp16a_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack4_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4to1_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack4to1.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4to1_fp16p_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack4to1_fp16p.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4to1_fp16s_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack4to1_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_group_pack4to1_fp16a_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_group_pack4to1_fp16a.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_pack4_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_pack4.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_pack4_fp16p_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_pack4_fp16p.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_pack4_fp16s_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_pack4_fp16s.spv.hex.h"
};
static const uint32_t deconvolutiondepthwise_pack4_fp16a_spv_data[] = {
#include "../_spir_v/deconvolutiondepthwise_pack4_fp16a.spv.hex.h"
};
static const uint32_t shufflechannel_spv_data[] = {
#include "../_spir_v/shufflechannel.spv.hex.h"
};
static const uint32_t shufflechannel_fp16p_spv_data[] = {
#include "../_spir_v/shufflechannel_fp16p.spv.hex.h"
};
static const uint32_t shufflechannel_fp16s_spv_data[] = {
#include "../_spir_v/shufflechannel_fp16s.spv.hex.h"
};
static const uint32_t shufflechannel_fp16a_spv_data[] = {
#include "../_spir_v/shufflechannel_fp16a.spv.hex.h"
};
static const uint32_t shufflechannel_pack4_spv_data[] = {
#include "../_spir_v/shufflechannel_pack4.spv.hex.h"
};
static const uint32_t shufflechannel_pack4_fp16p_spv_data[] = {
#include "../_spir_v/shufflechannel_pack4_fp16p.spv.hex.h"
};
static const uint32_t shufflechannel_pack4_fp16s_spv_data[] = {
#include "../_spir_v/shufflechannel_pack4_fp16s.spv.hex.h"
};
static const uint32_t shufflechannel_pack4_fp16a_spv_data[] = {
#include "../_spir_v/shufflechannel_pack4_fp16a.spv.hex.h"
};
static const uint32_t clip_spv_data[] = {
#include "../_spir_v/clip.spv.hex.h"
};
static const uint32_t clip_fp16p_spv_data[] = {
#include "../_spir_v/clip_fp16p.spv.hex.h"
};
static const uint32_t clip_fp16s_spv_data[] = {
#include "../_spir_v/clip_fp16s.spv.hex.h"
};
static const uint32_t clip_fp16a_spv_data[] = {
#include "../_spir_v/clip_fp16a.spv.hex.h"
};
static const uint32_t clip_pack4_spv_data[] = {
#include "../_spir_v/clip_pack4.spv.hex.h"
};
static const uint32_t clip_pack4_fp16p_spv_data[] = {
#include "../_spir_v/clip_pack4_fp16p.spv.hex.h"
};
static const uint32_t clip_pack4_fp16s_spv_data[] = {
#include "../_spir_v/clip_pack4_fp16s.spv.hex.h"
};
static const uint32_t clip_pack4_fp16a_spv_data[] = {
#include "../_spir_v/clip_pack4_fp16a.spv.hex.h"
};
static const uint32_t reorg_spv_data[] = {
#include "../_spir_v/reorg.spv.hex.h"
};
static const uint32_t reorg_fp16p_spv_data[] = {
#include "../_spir_v/reorg_fp16p.spv.hex.h"
};
static const uint32_t reorg_fp16s_spv_data[] = {
#include "../_spir_v/reorg_fp16s.spv.hex.h"
};
static const uint32_t reorg_fp16a_spv_data[] = {
#include "../_spir_v/reorg_fp16a.spv.hex.h"
};
static const uint32_t reorg_pack1to4_spv_data[] = {
#include "../_spir_v/reorg_pack1to4.spv.hex.h"
};
static const uint32_t reorg_pack1to4_fp16p_spv_data[] = {
#include "../_spir_v/reorg_pack1to4_fp16p.spv.hex.h"
};
static const uint32_t reorg_pack1to4_fp16s_spv_data[] = {
#include "../_spir_v/reorg_pack1to4_fp16s.spv.hex.h"
};
static const uint32_t reorg_pack1to4_fp16a_spv_data[] = {
#include "../_spir_v/reorg_pack1to4_fp16a.spv.hex.h"
};
static const uint32_t reorg_pack4_spv_data[] = {
#include "../_spir_v/reorg_pack4.spv.hex.h"
};
static const uint32_t reorg_pack4_fp16p_spv_data[] = {
#include "../_spir_v/reorg_pack4_fp16p.spv.hex.h"
};
static const uint32_t reorg_pack4_fp16s_spv_data[] = {
#include "../_spir_v/reorg_pack4_fp16s.spv.hex.h"
};
static const uint32_t reorg_pack4_fp16a_spv_data[] = {
#include "../_spir_v/reorg_pack4_fp16a.spv.hex.h"
};
static const uint32_t packing_1to4_spv_data[] = {
#include "../_spir_v/packing_1to4.spv.hex.h"
};
static const uint32_t packing_1to4_fp16p_spv_data[] = {
#include "../_spir_v/packing_1to4_fp16p.spv.hex.h"
};
static const uint32_t packing_1to4_fp16s_spv_data[] = {
#include "../_spir_v/packing_1to4_fp16s.spv.hex.h"
};
static const uint32_t packing_1to4_fp16a_spv_data[] = {
#include "../_spir_v/packing_1to4_fp16a.spv.hex.h"
};
static const uint32_t packing_4to1_spv_data[] = {
#include "../_spir_v/packing_4to1.spv.hex.h"
};
static const uint32_t packing_4to1_fp16p_spv_data[] = {
#include "../_spir_v/packing_4to1_fp16p.spv.hex.h"
};
static const uint32_t packing_4to1_fp16s_spv_data[] = {
#include "../_spir_v/packing_4to1_fp16s.spv.hex.h"
};
static const uint32_t packing_4to1_fp16a_spv_data[] = {
#include "../_spir_v/packing_4to1_fp16a.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_spv_data[] = {
#include "../_spir_v/cast_fp16_to_fp32.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_fp16p_spv_data[] = {
#include "../_spir_v/cast_fp16_to_fp32_fp16p.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_fp16s_spv_data[] = {
#include "../_spir_v/cast_fp16_to_fp32_fp16s.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_fp16a_spv_data[] = {
#include "../_spir_v/cast_fp16_to_fp32_fp16a.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_pack4_spv_data[] = {
#include "../_spir_v/cast_fp16_to_fp32_pack4.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_pack4_fp16p_spv_data[] = {
#include "../_spir_v/cast_fp16_to_fp32_pack4_fp16p.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_pack4_fp16s_spv_data[] = {
#include "../_spir_v/cast_fp16_to_fp32_pack4_fp16s.spv.hex.h"
};
static const uint32_t cast_fp16_to_fp32_pack4_fp16a_spv_data[] = {
#include "../_spir_v/cast_fp16_to_fp32_pack4_fp16a.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_spv_data[] = {
#include "../_spir_v/cast_fp32_to_fp16.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_fp16p_spv_data[] = {
#include "../_spir_v/cast_fp32_to_fp16_fp16p.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_fp16s_spv_data[] = {
#include "../_spir_v/cast_fp32_to_fp16_fp16s.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_fp16a_spv_data[] = {
#include "../_spir_v/cast_fp32_to_fp16_fp16a.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_pack4_spv_data[] = {
#include "../_spir_v/cast_fp32_to_fp16_pack4.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_pack4_fp16p_spv_data[] = {
#include "../_spir_v/cast_fp32_to_fp16_pack4_fp16p.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_pack4_fp16s_spv_data[] = {
#include "../_spir_v/cast_fp32_to_fp16_pack4_fp16s.spv.hex.h"
};
static const uint32_t cast_fp32_to_fp16_pack4_fp16a_spv_data[] = {
#include "../_spir_v/cast_fp32_to_fp16_pack4_fp16a.spv.hex.h"
};
static const uint32_t hardsigmoid_spv_data[] = {
#include "../_spir_v/hardsigmoid.spv.hex.h"
};
static const uint32_t hardsigmoid_fp16p_spv_data[] = {
#include "../_spir_v/hardsigmoid_fp16p.spv.hex.h"
};
static const uint32_t hardsigmoid_fp16s_spv_data[] = {
#include "../_spir_v/hardsigmoid_fp16s.spv.hex.h"
};
static const uint32_t hardsigmoid_fp16a_spv_data[] = {
#include "../_spir_v/hardsigmoid_fp16a.spv.hex.h"
};
static const uint32_t hardsigmoid_pack4_spv_data[] = {
#include "../_spir_v/hardsigmoid_pack4.spv.hex.h"
};
static const uint32_t hardsigmoid_pack4_fp16p_spv_data[] = {
#include "../_spir_v/hardsigmoid_pack4_fp16p.spv.hex.h"
};
static const uint32_t hardsigmoid_pack4_fp16s_spv_data[] = {
#include "../_spir_v/hardsigmoid_pack4_fp16s.spv.hex.h"
};
static const uint32_t hardsigmoid_pack4_fp16a_spv_data[] = {
#include "../_spir_v/hardsigmoid_pack4_fp16a.spv.hex.h"
};


