//TreeEnsembleRegressor
#version 450
struct Shape_t { uint n; uint c; uint d; uint h; uint w; };
layout(local_size_x_id = 0) in;
layout(local_size_y_id = 1) in;
layout(local_size_z_id = 2) in;  

layout(push_constant) uniform Parameters {      
    Shape_t X_t; Shape_t Y_t; int aggregate_function_t; int n_targets_t; Shape_t nodes_falsenodeids_t; Shape_t nodes_featureids_t; Shape_t nodes_missing_value_tracks_true_t; int* nodes_modes_t; Shape_t nodes_nodeids_t; Shape_t nodes_treeids_t; Shape_t nodes_truenodeids_t; int post_transform_t; Shape_t target_ids_t; Shape_t target_nodeids_t; Shape_t target_treeids_t;
} params;

layout(std430, binding = 0) buffer lay0 { float Y[]; };
layout(std430, binding = 1) buffer lay1 { float X[]; };


void main(){
    const uint id = gl_GlobalInvocationID.x; 
    const uint size = params.input.n * params.input.c * params.input.d * params.input.h * params.input.w;
    if(size <= id) {
        return;
    }
   
}
